import {
  registerChatCommand,
  whisperToCaller,
  type ChatCommandContext,
} from '../ChatCommands.js';

/**
 * !help — whisper a catalog of chat commands back to the caller.
 * Grouped by function so it's scannable. Kept as a static table
 * rather than a registry-introspection call: having human-written
 * one-liners per command is worth the duplication, and the list
 * changes slowly enough that drift is easy to catch in PR review.
 */

interface Entry { name: string; usage: string; dmOnly?: boolean; desc: string; }

const GROUPS: Array<{ title: string; entries: Entry[] }> = [
  {
    title: 'Combat — conditions',
    entries: [
      { name: 'cond', usage: '!cond <target> <name> [rounds]', dmOnly: true, desc: 'Apply a 5e condition; auto-expires if rounds given.' },
      { name: 'uncond', usage: '!uncond <target> <name>', dmOnly: true, desc: 'Clear a condition from a token.' },
      { name: 'rage', usage: '!rage [target]', desc: 'Enter Rage (+dmg/resist b-p-s) for 10 rounds.' },
      { name: 'unrage', usage: '!unrage [target]', desc: 'End Rage voluntarily.' },
      { name: 'inspire', usage: '!inspire <target>', dmOnly: true, desc: 'Award Inspiration — advantage on next roll.' },
      { name: 'uninspire', usage: '!uninspire [target]', desc: 'Spend / clear Inspiration.' },
      { name: 'assist', usage: '!assist <target>', desc: 'Help action — advantage on target\'s next attack or check.' },
      { name: 'unassist', usage: '!unassist [target]', desc: 'Clear the helped badge after the assisted action.' },
      { name: 'bardic', usage: '!bardic <target> [d6|d8|d10|d12]', desc: 'Bardic Inspiration — grant a bonus die.' },
      { name: 'unbardic', usage: '!unbardic <target> [add|waste]', desc: 'Spend (add: rolls die) or waste the Bardic Inspiration.' },
      { name: 'smite', usage: '!smite <1-5> [undead|fiend] [crit]', desc: 'Paladin Divine Smite — spends slot, rolls radiant dice.' },
      { name: 'secondwind', usage: '!secondwind', desc: 'Fighter Second Wind — bonus action, heal 1d10 + level.' },
      { name: 'actionsurge', usage: '!actionsurge', desc: 'Fighter Action Surge — grants an extra action this turn.' },
      { name: 'cunning', usage: '!cunning <dash|disengage|hide>', desc: 'Rogue Cunning Action — bonus action version.' },
      { name: 'protect', usage: '!protect <ally>', desc: 'Protection fighting style (reaction + shield) — ally within 5 ft gets attack-against disadvantage.' },
      { name: 'pam', usage: '!pam <target>', desc: 'Polearm Master butt-end strike (bonus action, 1d4 bludgeoning).' },
      { name: 'uncanny', usage: '!uncanny <dmg>', desc: 'Rogue Uncanny Dodge reaction — halves incoming damage.' },
      { name: 'evasion', usage: '!evasion <pass|fail> <dmg>', desc: 'Rogue/Monk Evasion — no damage on save, half on fail (refund applied dmg).' },
      { name: 'cuttingwords', usage: '!cuttingwords <enemy>', desc: 'Bard Lore reaction — spends BI die to subtract from enemy roll.' },
      { name: 'ki', usage: '!ki status | use <n> | reset | set <n>', desc: 'Monk Ki pool (defaults to level).' },
      { name: 'flurry', usage: '!flurry', desc: 'Monk Flurry of Blows — 2 unarmed strikes (1 ki, bonus action).' },
      { name: 'patient', usage: '!patient', desc: 'Monk Patient Defense — Dodge as bonus action (1 ki).' },
      { name: 'stepwind', usage: '!stepwind <dash|disengage>', desc: 'Monk Step of the Wind — Dash/Disengage as bonus action (1 ki).' },
      { name: 'stunstrike', usage: '!stunstrike <target> <dc>', desc: 'Monk Stunning Strike (L5, 1 ki) — CON save vs stunned.' },
      { name: 'sp', usage: '!sp status | use <n> | reset | set <n>', desc: 'Sorcerer Sorcery Point pool.' },
      { name: 'meta', usage: '!meta <careful|distant|empowered|extended|heightened|quickened|seeking|subtle|twinned [lvl]>', desc: 'Sorcerer Metamagic — burns SP + announces effect.' },
      { name: 'flexible', usage: '!flexible slot2sp <lvl> | sp2slot <lvl>', desc: 'Sorcerer Flexible Casting — convert slots ↔ sorcery points.' },
      { name: 'xp', usage: '!xp <target…> <amount> | threshold | report', desc: 'Award XP (DM) or check thresholds + level ups.' },
      { name: 'wildshape', usage: '!wildshape <beast> <hp> [ac] [speed]', desc: 'Druid Wild Shape — announce + track beast HP pool.' },
      { name: 'revert', usage: '!revert', desc: 'Revert Wild Shape back to Druid form.' },
      { name: 'beast', usage: '!beast dmg|heal|status <n>', desc: 'Apply damage/heal to Wild-Shape beast pool.' },
      { name: 'reckless', usage: '!reckless', desc: 'Barbarian Reckless Attack — toggle until next turn.' },
      { name: 'endurance', usage: '!endurance | reset | status', desc: 'Half-Orc Relentless Endurance — drop to 1 HP instead of 0 (1/long rest).' },
      { name: 'arcanerecovery', usage: '!arcanerecovery', desc: 'Wizard short-rest slot recovery — announces budget.' },
      { name: 'breath', usage: '!breath <dice>/<ability>/<dc> <target1> […]', desc: 'Dragonborn Breath Weapon — rolls each target\'s save + applies damage.' },
      { name: 'eldritch', usage: '!eldritch <bolts> <cha-mod> [label]', desc: 'Eldritch Blast — rolls N beams, +CHA per beam with Agonizing Blast.' },
      { name: 'superiority', usage: '!superiority status | use | reset', desc: 'Battle Master Superiority Dice pool.' },
      { name: 'maneuver', usage: '!maneuver <name> [target] [dc]', desc: 'Battle Master maneuver — spends sup die, auto-rolls save if trip/pushing/disarming/menacing.' },
      { name: 'crit', usage: '!crit <d20>', desc: 'Champion Improved Crit check — is that 19 a crit for you?' },
      { name: 'encounter', usage: '!encounter <cr1> [cr2 …]', desc: 'Whisper the adjusted XP + difficulty rating (easy/medium/hard/deadly).' },
      { name: 'hd', usage: '!hd <n> [dN]', desc: 'Spend N Hit Dice — rolls from the sheet pool, adds CON × N, heals HP.' },
      { name: 'indomitable', usage: '!indomitable', desc: 'Fighter L9: reroll a failed save (1/2/3 per long rest at L9/L13/L17).' },
      { name: 'reliable', usage: '!reliable <d20>', desc: 'Rogue L11: treat d20<10 as 10 on proficient check.' },
      { name: 'lucky1', usage: '!lucky1 <d20>', desc: 'Halfling Lucky racial: reroll natural 1, must keep the new roll.' },
      { name: 'divinesense', usage: '!divinesense', desc: 'Paladin Divine Sense — detect celestial/fiend/undead in 60 ft.' },
      { name: 'songofrest', usage: '!songofrest', desc: 'Bard L2 — allies spending HD on short rest gain +d6/d8/d10/d12 HP.' },
      { name: 'surge', usage: '!surge', desc: 'Wild Magic Sorcerer — roll d100 on the chaos table.' },
      { name: 'ward', usage: '!ward status|init|dmg|heal|reset [n]', desc: 'Abjuration Wizard Arcane Ward HP pool.' },
      { name: 'courage', usage: '!courage', desc: 'Paladin L10 Aura of Courage — clears frightened from allies in radius.' },
      { name: 'sculpt', usage: '!sculpt <spell-level>', desc: 'Evocation Wizard Sculpt Spells — announce how many allies to exempt.' },
      { name: 'portent', usage: '!portent roll | use <d20> | list', desc: 'Diviner Wizard L2 — reserve 2-3 d20 rolls at dawn, swap into any roll.' },
      { name: 'colossus', usage: '!colossus', desc: 'Hunter Ranger L3 — +1d8 damage once/turn vs wounded target.' },
      { name: 'assassinate', usage: '!assassinate <target> <atk-bonus> [surprised]', desc: 'Assassin Rogue L3 — adv vs not-yet-acted, auto-crit on surprised.' },
      { name: 'guided', usage: '!guided', desc: 'War Cleric Channel Divinity — +10 to the attack roll just made.' },
      { name: 'hbc', usage: '!hbc <target> | clear <target>', desc: 'Hexblade\'s Curse — +prof dmg, 19-20 crit, HP regen on kill.' },
      { name: 'wrath', usage: '!wrath <attacker> <dc> [lightning|thunder]', desc: 'Tempest Cleric reaction — 2d8 on DEX save fail.' },
      { name: 'bear', usage: '!bear on | off', desc: 'Barbarian Bear Totem — resist all but psychic while raging.' },
      { name: 'stillness', usage: '!stillness', desc: 'Monk L7 — action: clears charmed + frightened on self.' },
      { name: 'fasthands', usage: '!fasthands [label]', desc: 'Thief Rogue L3 — bonus action Object Use / Sleight of Hand / Thieves\' Tools.' },
      { name: 'sacredweapon', usage: '!sacredweapon', desc: 'Devotion Paladin CD — +CHA attack, magical, shed light (1 min).' },
      { name: 'vow', usage: '!vow <target>', desc: 'Vengeance Paladin CD — advantage on attacks vs target (1 min).' },
      { name: 'discipleoflife', usage: '!discipleoflife <spell-level>', desc: 'Life Cleric — heal spells give +2 + level extra HP.' },
      { name: 'darkblessing', usage: '!darkblessing', desc: 'Fiend Warlock — gain CHA+level temp HP on kill.' },
      { name: 'feypresence', usage: '!feypresence <charm|fear> <target1> [target2 …]', desc: 'Archfey Warlock — WIS save vs charm/fear in 10 ft cube.' },
      { name: 'wardingflare', usage: '!wardingflare <attacker>', desc: 'Light Cleric reaction — impose disadvantage on an attack.' },
      { name: 'grimharvest', usage: '!grimharvest <spell-level> [necro]', desc: 'Necromancy Wizard — regain 2× (or 3× for necromancy) spell-level HP on kill.' },
      { name: 'healinglight', usage: '!healinglight <target> <n-dice> | status | reset', desc: 'Celestial Warlock — pool of d6 heals, bonus action (1+level dice, max level/spend).' },
      { name: 'awakened', usage: '!awakened <target> | <message>', desc: 'Great Old One Warlock — telepathic contact within 30 ft.' },
      { name: 'frenzy', usage: '!frenzy [attack|end]', desc: 'Berserker Barbarian — while raging, bonus-action melee attacks; +1 exhaustion on end.' },
      { name: 'spiritshield', usage: '!spiritshield <ally> <incoming-dmg>', desc: 'Ancestral Guardian L6 reaction — 2d6/3d6/4d6 damage reduction for ally in 30 ft.' },
      { name: 'draconicresilience', usage: '!draconicresilience', desc: 'Draconic Sorcerer — whisper natural AC (13+DEX) + HP bonus (+1/level).' },
      { name: 'elemental', usage: '!elemental [resist]', desc: 'Draconic Sorcerer L6 — +CHA to ancestry-type spell dmg, or spend 1 SP for resistance.' },
      { name: 'moondruid', usage: '!moondruid shape | heal <slot>', desc: 'Moon Druid L2 — Wild Shape as bonus action, or burn slot to heal 1d8/level.' },
      { name: 'footwork', usage: '!footwork <target>', desc: 'Swashbuckler L3 — target you attacked can\'t OA you this turn.' },
      { name: 'rakish', usage: '!rakish init | sneak', desc: 'Swashbuckler L3 — +CHA to initiative; 1v1 Sneak Attack without advantage.' },
      { name: 'fightingspirit', usage: '!fightingspirit', desc: 'Samurai L3 — bonus action, adv on attacks this turn + 5/10/15 temp HP.' },
      { name: 'echo', usage: '!echo summon <x> <y> | swap | attack | dismiss', desc: 'Echo Knight L3 — manifest the echo, teleport-swap, attack from echo.' },
      { name: 'cavmark', usage: '!cavmark <target>', desc: 'Cavalier L3 — Unwavering Mark: disadv vs others, reaction-attack if they swing away.' },
      { name: 'warding', usage: '!warding <ally>', desc: 'Cavalier L7 reaction — +1d8 to ally AC + DEX save vs one attack.' },
      { name: 'wildbarb', usage: '!wildbarb', desc: 'Wild Magic Barbarian — roll d8 on the surge table when entering Rage.' },
      { name: 'divinefury', usage: '!divinefury [necro]', desc: 'Zealot L3 — first melee hit/turn +1d6+half-level radiant (or necrotic).' },
      { name: 'openhand', usage: '!openhand <target> <dc> <prone|push|noreact>', desc: 'Open Hand Monk — on Flurry hit: save vs prone/push or no reactions.' },
      { name: 'grave', usage: '!grave <damage-taken>', desc: 'Shadow Sorcerer — CHA save DC 5+dmg to drop to 1 HP instead of 0.' },
      { name: 'hound', usage: '!hound <target>', desc: 'Shadow Sorcerer L3 — 3 SP, summon spectral wolf; disadv saves vs your spells in 5 ft.' },
      { name: 'mantle', usage: '!mantle <target1> [target2 …]', desc: 'Glamour Bard L3 — BI die grants 5/8/11/14 temp HP + free reaction move to CHA targets.' },
      { name: 'enthrall', usage: '!enthrall <target1> [target2 …] <dc>', desc: 'Glamour Bard L3 — WIS save vs charmed for 1 hr (up to CHA mod targets).' },
      { name: 'lay', usage: '!lay <target> <amount>', desc: 'Paladin Lay on Hands — heal target (track ≤ 5*level/day).' },
      { name: 'channel', usage: '!channel <effect>', desc: 'Cleric / Paladin Channel Divinity — DM-narrated effect.' },
      { name: 'power', usage: '!power [target] [on|off]', desc: 'GWM / Sharpshooter -5 / +10 toggle.' },
      { name: 'cover', usage: '!cover <target> <none|half|three|full>', dmOnly: true, desc: '+0 / +2 / +5 AC cover bonuses.' },
    ],
  },
  {
    title: 'Combat — DM turn hooks',
    entries: [
      { name: 'onturn', usage: '!onturn <target> <message>', dmOnly: true, desc: 'Broadcast <message> when <target>\'s turn starts.' },
      { name: 'onround', usage: '!onround <message>', dmOnly: true, desc: 'Broadcast at the start of each new round.' },
      { name: 'unhook', usage: '!unhook <target|round> [index]', dmOnly: true, desc: 'Clear queued hooks.' },
    ],
  },
  {
    title: 'Rests',
    entries: [
      { name: 'rest', usage: '!rest <short|long> [target]', dmOnly: true, desc: 'Trigger a rest on the whole party or a single target — runs performLongRest/ShortRest on each PC\'s client.' },
    ],
  },
  {
    title: 'Attunement',
    entries: [
      { name: 'attune', usage: '!attune <item> | list', desc: 'Attune to an item in your inventory (cap: 3).' },
      { name: 'unattune', usage: '!unattune <item>', desc: 'Break attunement with an item.' },
    ],
  },
  {
    title: 'Combat — maneuvers',
    entries: [
      { name: 'grapple', usage: '!grapple <target>', desc: 'Caller Athletics vs target Athletics/Acrobatics — on win, target is grappled.' },
      { name: 'shove', usage: '!shove <target> [prone|push]', desc: 'Caller Athletics vs target Athletics/Acrobatics — on win, target is knocked prone (default) or shoved 5 ft.' },
      { name: 'legendary', usage: '!legendary <target> [action] | set <target> <max> | clear <target>', desc: 'Monster legendary-action budget. Spends one, refreshes on monster\'s own turn.' },
      { name: 'legres', usage: '!legres <target> | set <target> <max> | list | reset', desc: 'Legendary Resistance pool. Spend one to flip a failed save into a success.' },
      { name: 'lair', usage: '!lair enable|disable <target> | <target> <action> | list', desc: 'Lair actions — reminder at round start (init 20). DM narrates the action.' },
      { name: 'recharge', usage: '!recharge set <target> <ability> <min> | use <target> <ability> | list <target> | clear <target>', desc: 'Track monster recharge abilities (breath weapon). Auto-rolls 1d6 on turn start.' },
    ],
  },
  {
    title: 'HP / damage',
    entries: [
      { name: 'hp', usage: '!hp <target> <value>', dmOnly: true, desc: 'Set a token\'s current HP.' },
      { name: 'damage', usage: '!damage <target> <amount>', dmOnly: true, desc: 'Subtract HP, fires concentration save.' },
      { name: 'heal', usage: '!heal <target> <amount>', dmOnly: true, desc: 'Add HP up to max.' },
      { name: 'thp', usage: '!thp <amount> [target]', desc: 'Set temp HP — 0 clears, higher replaces, lower keeps existing (RAW).' },
      { name: 'potion', usage: '!potion <target> [dice]', desc: 'Drink a healing potion (default 2d4+2).' },
      { name: 'stabilize', usage: '!stabilize <target>', desc: 'Medicine DC 10 — stabilize a 0-HP creature.' },
      { name: 'setattr', usage: '!setattr <target> <attr> <value>', dmOnly: true, desc: 'Edit a character sheet column directly (name, level, class, race, etc.).' },
    ],
  },
  {
    title: 'Damage riders / concentration spells',
    entries: [
      { name: 'hex', usage: '!hex <target> / !unhex', desc: 'Warlock Hex — caster\'s attacks deal +1d6 necrotic vs target.' },
      { name: 'mark', usage: '!mark <target> / !unmark', desc: 'Ranger Hunter\'s Mark — caster\'s weapon attacks deal +1d6.' },
      { name: 'turnundead', usage: '!turnundead <target> [target2 …]', desc: 'Cleric/Paladin CD — WIS save vs fright for 1 min.' },
      { name: 'bless', usage: '!bless <target1> [target2] [target3]', desc: 'Apply blessed (+1d4 attacks + saves, 10 rounds).' },
      { name: 'bane', usage: '!bane <target1> [target2] [target3] <dc>', desc: 'Apply baned (-1d4 attacks + saves, 10 rounds).' },
      { name: 'faeriefire', usage: '!faeriefire <target1> [target2 …] <dc>', desc: 'Apply outlined (adv to attackers, no invisibility).' },
      { name: 'holdperson', usage: '!holdperson <target> <dc>', desc: 'Paralyze a humanoid. WIS save at end of each turn, 1 min.' },
      { name: 'holdmonster', usage: '!holdmonster <target> <dc>', desc: 'Paralyze any creature. WIS save at end of each turn.' },
      { name: 'sleep', usage: '!sleep <target>', desc: 'Knock target unconscious. Ends on any damage. 1 min max.' },
      { name: 'fear', usage: '!fear <target> <dc>', desc: 'Frighten target for 1 min. WIS save at end of each turn.' },
      { name: 'slow', usage: '!slow <target> <dc>', desc: 'Slow target for 1 min. -2 AC/DEX, half speed, no reactions.' },
      { name: 'ritual', usage: '!ritual <spell>', desc: 'Cast a ritual-tagged spell without a slot (+10 min).' },
      { name: 'components', usage: '!components <spell>', desc: 'Check V/S/M components — warns if silenced or hands full.' },
      { name: 'healingword', usage: '!healingword <target> [slot]', desc: 'Bonus action 60 ft heal — 1d4+mod (+1d4/slot above 1st).' },
      { name: 'curewounds', usage: '!curewounds <target> [slot]', desc: 'Action touch heal — 1d8+mod (+1d8/slot above 1st).' },
      { name: 'masshealingword', usage: '!masshealingword <t1> [t2 …] [slot]', desc: 'Bonus action mass heal — 1d4+mod to up to 6 targets within 60 ft.' },
      { name: 'guidingbolt', usage: '!guidingbolt <target> [slot]', desc: 'Ranged spell atk, 4d6 radiant + next attack vs target has adv.' },
      { name: 'thunderwave', usage: '!thunderwave <t1> [t2 …] [slot]', desc: '15-ft cube, CON save, 2d8 thunder + push 10.' },
      { name: 'spiritualweapon', usage: '!spiritualweapon <target> [slot]', desc: 'Bonus action spell atk, 1d8+mod force. Scales 2/3/4/5d8.' },
      { name: 'spiritguardians', usage: '!spiritguardians <t1> [t2 …] [slot]', desc: '15-ft aura, WIS save, 3d8 radiant (half on save), halves speed.' },
      { name: 'command', usage: '!command <target> <approach|drop|flee|grovel|halt>', desc: 'WIS save — target obeys 1-word command on next turn.' },
      { name: 'sanctuary', usage: '!sanctuary <ally>', desc: 'Bonus action ward — attackers make WIS save or pick another target. Conc 1 min.' },
      { name: 'banishment', usage: '!banishment <target> [slot]', desc: 'CHA save — banish to another plane (concentration, 1 min).' },
      { name: 'silverybarbs', usage: '!silverybarbs <enemy> <ally>', desc: 'Reaction — force success reroll on enemy + advantage for ally.' },
      { name: 'counterspell', usage: '!counterspell <caster> <spell-lvl> [my-slot]', desc: 'Reaction — auto if my-slot ≥ spell-lvl, else DC 10+lvl ability check.' },
      { name: 'dispelmagic', usage: '!dispelmagic <target> <effect-lvl> [my-slot]', desc: 'Same rules as counterspell but for an active effect.' },
      { name: 'fireball', usage: '!fireball <t1> [t2 …] [slot]', desc: '20-ft sphere, DEX, 8d6 fire (+1d6/slot).' },
      { name: 'lightningbolt', usage: '!lightningbolt <t1> [t2 …] [slot]', desc: '100-ft line, DEX, 8d6 lightning (+1d6/slot).' },
      { name: 'magicmissile', usage: '!magicmissile <t1> [t2 t3 …] [slot]', desc: 'Auto-hit, 3× 1d4+1 force (+1/slot). Round-robin if fewer targets.' },
      { name: 'scorchingray', usage: '!scorchingray <t1> [t2 t3] [slot]', desc: '3× ranged-atk rays, 2d6 fire each (+1 ray/slot).' },
      { name: 'coneofcold', usage: '!coneofcold <t1> [t2 …] [slot]', desc: '60-ft cone, CON, 8d8 cold (+1d8/slot).' },
      { name: 'shatter', usage: '!shatter <t1> [t2 …] [slot]', desc: '10-ft radius, CON, 3d8 thunder (+1d8/slot).' },
      { name: 'entangle', usage: '!entangle <t1> [t2 …]', desc: '20-ft square, STR, restrained (end-of-turn STR to break).' },
      { name: 'web', usage: '!web <t1> [t2 …]', desc: '20-ft cube, DEX, restrained (STR save to break), 1 hr conc.' },
      { name: 'moonbeam', usage: '!moonbeam <t1> [t2 …] [slot]', desc: '5-ft cylinder, CON, 2d10 radiant (+1d10/slot).' },
      { name: 'calllightning', usage: '!calllightning <t1> [t2 …] [slot]', desc: '5-ft cylinder from above, DEX, 3d10 lightning (+1d10/slot).' },
      { name: 'mistystep', usage: '!mistystep', desc: 'Bonus action, teleport 30 ft.' },
      { name: 'aid', usage: '!aid <t1> [t2] [t3] [slot]', desc: '+5 max/current HP per target (8 hrs).' },
      { name: 'revivify', usage: '!revivify <target>', desc: 'Return a creature dead <1 min to 1 HP.' },
      { name: 'invisibility', usage: '!invisibility <target>', desc: 'L2 concentration 1 hr invisibility.' },
      { name: 'greaterinvisibility', usage: '!greaterinvisibility <target>', desc: 'L4 concentration 1 min; invisible even while attacking.' },
      { name: 'haste', usage: '!haste <target>', desc: 'L3 conc; +2 AC, adv DEX, 2× speed, extra action.' },
      { name: 'fly', usage: '!fly <t1> [t2 …] [slot]', desc: '60-ft fly speed, concentration 10 min.' },
      { name: 'passwithouttrace', usage: '!passwithouttrace', desc: '+10 Stealth + no tracks for all within 30 ft, 1 hr conc.' },
      { name: 'lesserrestoration', usage: '!lesserrestoration <target> <cond>', desc: 'Cure poisoned/paralyzed/blinded/deafened/disease.' },
      { name: 'greaterrestoration', usage: '!greaterrestoration <target> <eff>', desc: 'Reduce 1 exhaustion / end charm / remove petrify.' },
      { name: 'blur', usage: '!blur', desc: 'Self-buff: attacks against have disadvantage, 1 min conc.' },
      { name: 'stoneskin', usage: '!stoneskin <target>', desc: 'Resist non-magical BPS, 1 hr conc.' },
      { name: 'deathward', usage: '!deathward <target>', desc: 'First drop to 0 HP becomes 1 HP. 8 hrs.' },
      { name: 'alacrity', usage: '!alacrity <target> | clear <target>', desc: 'Gift of Alacrity (Graviturgy Wizard L2) — target adds +1d8 to initiative rolls while concentration holds.' },
    ],
  },
  {
    title: 'Subclass — Channel Divinity + Cleric/Paladin',
    entries: [
      { name: 'forgeblessing', usage: '!forgeblessing <target>', desc: 'Forge Cleric — +1 armor AC or +1 weapon atk/dmg for 24 hrs.' },
      { name: 'pathtograve', usage: '!pathtograve <target>', desc: 'Grave Cleric CD — next attack vs target has vulnerability to all damage.' },
      { name: 'voice', usage: '!voice <ally>', desc: 'Order Cleric — after casting L1+ on ally, ally gets reaction weapon attack.' },
      { name: 'emboldenbond', usage: '!emboldenbond <t1> <t2> [t3 …]', desc: 'Peace Cleric — bond up to PB creatures for 10 min (+1d4, 1/turn).' },
      { name: 'twilightsanct', usage: '!twilightsanct <target> <thp|clear>', desc: 'Twilight Cleric CD reaction — 1d6+level temp HP OR end charm/fright.' },
      { name: 'trickstersblessing', usage: '!trickstersblessing <ally>', desc: 'Trickery Cleric — advantage on Stealth for 1 hour.' },
      { name: 'natureswrath', usage: '!natureswrath <target>', desc: 'Ancients Paladin CD — STR/DEX save vs restrained (end-of-turn).' },
      { name: 'conquer', usage: '!conquer <t1> [t2 …]', desc: 'Conquest Paladin CD — 30 ft WIS save vs frightened 1 min.' },
      { name: 'challenge', usage: '!challenge <t1> [t2 …]', desc: "Crown Paladin CD — 30 ft WIS save vs can't move > 30 ft from caster." },
      { name: 'dread', usage: '!dread <t1> [t2 …]', desc: 'Oathbreaker CD — 30 ft WIS save vs frightened 1 min (no mid-save).' },
      { name: 'rebuke', usage: '!rebuke <attacker> <dmg-dealt>', desc: 'Redemption Paladin CD reaction — radiant dmg to attacker, WIS save half.' },
    ],
  },
  {
    title: 'Subclass — Fighter + Rogue expansions',
    entries: [
      { name: 'arcaneshot', usage: '!arcaneshot <option> <target>', desc: 'Arcane Archer — banishing/beguiling/bursting/grasping/piercing/seeking/shadow/slowing.' },
      { name: 'rally', usage: '!rally <t1> [t2 t3]', desc: 'Banneret/Purple Dragon — up to 3 allies within 60 ft gain level temp HP.' },
      { name: 'psidie', usage: '!psidie [reset]', desc: 'Psi Warrior Psionic Power dice (d6→d12 by level). Reset on short rest.' },
      { name: 'psistrike', usage: '!psistrike <target>', desc: 'Psi Warrior — spend 1 die, add +1d+INT force damage on hit.' },
      { name: 'psifield', usage: '!psifield <ally> <dmg>', desc: 'Psi Warrior reaction — spend 1 die, reduce dmg by 1d+INT for ally in 30 ft.' },
      { name: 'giantsmight', usage: '!giantsmight', desc: 'Rune Knight — bonus action, Large size + adv STR + bonus dmg die.' },
      { name: 'rune', usage: '!rune <cloud|fire|frost|hill|stone|storm>', desc: 'Rune Knight — invoke rune effect (1/short rest each).' },
      { name: 'helpat', usage: '!helpat <target>', desc: 'Mastermind — Help as bonus action, up to 30 ft.' },
      { name: 'insightfight', usage: '!insightfight <target>', desc: 'Inquisitive — Insight vs Deception: 1 min no-adv Sneak Attack on win.' },
      { name: 'skirmish', usage: '!skirmish', desc: 'Scout reaction — move half speed without OA when enemy ends turn within 5 ft.' },
      { name: 'psyblade', usage: '!psyblade <target> [bonus]', desc: 'Soulknife — primary or offhand psychic blade attack.' },
      { name: 'psiknife', usage: '!psiknife [reset]', desc: 'Soulknife Psionic Power dice pool.' },
      { name: 'psiknack', usage: '!psiknack', desc: 'Soulknife — spend 1 die, reroll a failed proficient skill check.' },
    ],
  },
  {
    title: 'Feats',
    entries: [
      { name: 'alert', usage: '!alert', desc: 'Alert feat — +5 init, un-surprise-able, hidden attackers no adv.' },
      { name: 'crossbowexpert', usage: '!crossbowexpert <target>', desc: 'Bonus-action hand crossbow attack.' },
      { name: 'shieldmaster', usage: '!shieldmaster <target> <prone|push>', desc: 'Bonus-action shove with shield (contested).' },
      { name: 'sentinel', usage: '!sentinel <attacker>', desc: 'Reaction melee attack vs enemy attacking an ally in reach.' },
      { name: 'mobile', usage: '!mobile [attacked-target]', desc: 'No OA from target you attacked this turn; +10 speed passive.' },
      { name: 'savageattacker', usage: '!savageattacker <dmg1> <dmg2>', desc: 'Keep the higher of two damage rolls (1/turn).' },
      { name: 'warcaster', usage: '!warcaster [oa]', desc: 'War Caster: adv conc saves, reaction spell in place of OA.' },
      { name: 'inspiringleader', usage: '!inspiringleader <t1> [t2 …]', desc: '10-min speech: CHA+level temp HP to up to 6 allies.' },
      { name: 'tavernbrawler', usage: '!tavernbrawler <target>', desc: 'Unarmed d4 + grapple on hit.' },
      { name: 'heavyarmormaster', usage: '!heavyarmormaster <dmg>', desc: 'Reduce non-magical BPS damage by 3.' },
      { name: 'elementaladept', usage: '!elementaladept <type>', desc: 'Ignore resistance to chosen damage type (1s → 2s).' },
    ],
  },
  {
    title: 'Race features',
    entries: [
      { name: 'radiantsoul', usage: '!radiantsoul', desc: 'Aasimar Protector L3 — fly + bonus radiant dmg 1 min.' },
      { name: 'infernallegacy', usage: '!infernallegacy [spell]', desc: 'Tiefling thaumaturgy/hellishrebuke/darkness.' },
      { name: 'stonesendurance', usage: '!stonesendurance <dmg>', desc: 'Goliath reaction — reduce dmg by 1d12+CON.' },
      { name: 'hiddenstep', usage: '!hiddenstep', desc: 'Firbolg — bonus action invisibility until end of next turn.' },
      { name: 'felinestep', usage: '!felinestep', desc: 'Tabaxi — double speed this turn.' },
      { name: 'feystep', usage: '!feystep [autumn|winter|spring|summer]', desc: 'Eladrin — 30 ft teleport with seasonal kicker.' },
      { name: 'magicres', usage: '!magicres', desc: 'Yuan-Ti/Satyr/Gnome — advantage on all spell saves.' },
      { name: 'savageattacks', usage: '!savageattacks', desc: 'Half-Orc — extra weapon die on melee crit.' },
      { name: 'mimicry', usage: '!mimicry <sound>', desc: 'Kenku — perfectly mimic a sound.' },
      { name: 'shift', usage: '!shift', desc: 'Shifter — bonus action, level+CON temp HP for 1 min.' },
    ],
  },
  {
    title: 'Magic items',
    entries: [
      { name: 'wand', usage: '!wand <target> <darts> | recharge', desc: 'Wand of Magic Missiles — 7 charges, 1d6+1 recharge/dawn.' },
      { name: 'staffheal', usage: '!staffheal <target> <cure|lesser|mass> [slot]', desc: 'Staff of Healing — 10 charges, Cure Wounds / Lesser / Mass Cure.' },
      { name: 'potionplus', usage: '!potionplus <target> <healing|greater|superior|supreme>', desc: 'Potion tiers: 2d4+2 / 4d4+4 / 8d4+8 / 10d4+20.' },
      { name: 'bagofholding', usage: '!bagofholding in|out|check <item> <lbs>', desc: 'Track capacity (500 lbs).' },
      { name: 'deck', usage: '!deck', desc: 'Draw from Deck of Many Things (d13 sample).' },
      { name: 'scroll', usage: '!scroll <spell>', desc: 'Consume a spell scroll; DC check if not on list.' },
      { name: 'magicitem', usage: '!magicitem <slug> [wearer] | list | help <slug>', desc: '30+ magic items catalog: +1/+2/+3 weapons + armor, Cloak / Ring of Protection, Gauntlets of Ogre Power, Boots of Speed, Sun Blade, Flame Tongue, Holy Avenger, Vorpal Sword, Staff of Power, Staff of the Magi, etc.' },
    ],
  },
  {
    title: 'Spells — Tier 21 (high-level + signature)',
    entries: [
      { name: 'hypnoticpattern', usage: '!hypnoticpattern <t1> [t2 …]', desc: 'L3, 30-ft cube, WIS save vs charmed + incapacitated, breaks on damage.' },
      { name: 'dominateperson', usage: '!dominateperson <target> [slot]', desc: 'L5, WIS save vs charmed, save at end of turn / on damage.' },
      { name: 'dominatemonster', usage: '!dominatemonster <target> [slot]', desc: 'L8 upgrade of Dominate Person — any creature.' },
      { name: 'dominatebeast', usage: '!dominatebeast <target> [slot]', desc: 'L4 Druid/Sorcerer — WIS save, beasts only.' },
      { name: 'polymorph', usage: '!polymorph <target> <beast-CR>', desc: 'L4, WIS save — transform into CR ≤ X beast for 1 hr concentration.' },
      { name: 'truepolymorph', usage: '!truepolymorph <target>', desc: 'L9 — any creature/object, concentration 1 hr → permanent.' },
      { name: 'feeblemind', usage: '!feeblemind <target>', desc: 'L8 — INT DC save, 4d8 psychic + INT/CHA → 1 until cured.' },
      { name: 'stinkingcloud', usage: '!stinkingcloud <t1> [t2 …]', desc: 'L3 — CON save vs incapacitated; save at end of each turn.' },
      { name: 'cloudkill', usage: '!cloudkill <t1> [t2 …] [slot]', desc: 'L5 — 5d8 poison, half on CON save; moves 10 ft/turn (+1d8/slot).' },
      { name: 'meteorswarm', usage: '!meteorswarm <t1> [t2 …]', desc: 'L9 — 4×40-ft radius, 20d6 fire + 20d6 bludgeoning, DEX half.' },
      { name: 'powerwordkill', usage: '!powerwordkill <target>', desc: 'L9, no save — if target HP ≤ 100, instant death.' },
      { name: 'powerwordstun', usage: '!powerwordstun <target>', desc: 'L8, no save — if target HP ≤ 150, stunned; CHA save at end of turn.' },
      { name: 'wallofforce', usage: '!wallofforce', desc: 'L5 — panel/sphere, conc 1 min. Impassable by physical or magical.' },
      { name: 'walloffire', usage: '!walloffire', desc: 'L4 — 5d8 fire to creatures passing or in area, conc 1 min.' },
      { name: 'wallofstone', usage: '!wallofstone', desc: 'L5 — 10×10 panels, AC 15 / 30 HP each; permanent if held 10 min.' },
      { name: 'wallofice', usage: '!wallofice', desc: 'L6 — AC 12/30 HP, vulnerable to fire; 5d6 cold on break.' },
      { name: 'wish', usage: '!wish [intent]', desc: 'L9 — 5 hard-coded effects or freeform (33% never cast again + exhaustion).' },
      { name: 'simulacrum', usage: '!simulacrum <creature>', desc: 'L7 — half-strength duplicate (1500 gp diamond + snow).' },
      { name: 'scrying', usage: '!scrying <target>', desc: 'L5 — WIS save; on fail, sensor within 10 ft of target for 10 min.' },
      { name: 'teleport', usage: '!teleport [destination]', desc: 'L7 — self + 8 allies; d100 mishap table for familiarity rolls.' },
      { name: 'planeshift', usage: '!planeshift <plane> [t1 t2 …]', desc: 'L7 — self+8 or CHA save to banish unwilling.' },
      { name: 'gate', usage: '!gate [plane]', desc: 'L9 — planar portal 5-20 ft; names pull creatures through.' },
      { name: 'trueseeing', usage: '!trueseeing <target>', desc: 'L6 — 120 ft truesight 1 hr (Ethereal, invisible, illusions).' },
      { name: 'glyph', usage: '!glyph [type]', desc: 'L3 — inscribed rune w/ stored spell or 5d8 explosive (DEX half).' },
      { name: 'contingency', usage: '!contingency <spell> | <trigger>', desc: 'L6 — pre-load spell to self-cast when trigger fires.' },
      { name: 'massheal', usage: '!massheal <t1> [t2 …]', desc: 'L9 — 700 HP pool spread across up to 12 targets in 60 ft.' },
      { name: 'masscurewounds', usage: '!masscurewounds <t1> [t2 …] [slot]', desc: 'L5 — 3d8+mod to up to 6 in 30-ft radius (+1d8/slot).' },
    ],
  },
  {
    title: 'Resurrection + ongoing damage',
    entries: [
      { name: 'raisedead', usage: '!raisedead <target>', desc: 'L5, 500 gp diamond — dead ≤ 10 days, return at 1 HP + -4 penalty 4 days.' },
      { name: 'resurrection', usage: '!resurrection <target>', desc: 'L7, 1000 gp — dead ≤ 100 yrs, full HP + -4 penalty 96 hrs.' },
      { name: 'trueresurrection', usage: '!trueresurrection <target>', desc: 'L9, 25,000 gp — dead ≤ 200 yrs, full HP, perfect health, no penalty.' },
      { name: 'reincarnate', usage: '!reincarnate <target>', desc: 'L5, 1000 gp — new random race (d14 table), dead ≤ 10 days.' },
      { name: 'gentlerepose', usage: '!gentlerepose <corpse>', desc: 'L2 ritual — preserve a corpse 10 days (extends res-spell window).' },
      { name: 'burning', usage: '!burning <target> <dice> <die>', desc: 'Apply ongoing fire damage per turn. Pairs with !burningtick / !burningstop.' },
      { name: 'bleeding', usage: '!bleeding <target> <dice> <die>', desc: 'Apply ongoing necrotic damage per turn. Pairs with !bleedingtick / !bleedingstop.' },
      { name: 'acidsplash', usage: '!acidsplash <target> <dice> <die>', desc: 'Apply ongoing acid damage per turn. Pairs with !acidsplashtick / !acidsplashstop.' },
    ],
  },
  {
    title: 'XGE / TCE subclass features (Tier 25)',
    entries: [
      { name: 'gloomstalker', usage: '!gloomstalker', desc: 'Ranger (Gloom Stalker) — Dread Ambusher: +WIS initiative, +1d8 on turn-1 extra attack.' },
      { name: 'horizonwalker', usage: '!horizonwalker', desc: 'Ranger — Planar Warrior: +1d8 force damage on marked target (+2d8 L11).' },
      { name: 'monsterslayer', usage: '!monsterslayer <target>', desc: "Ranger — Slayer's Prey: mark a target, +1d6 on 1st attack/turn." },
      { name: 'eldritchknight', usage: '!eldritchknight <bond|warmagic|strike>', desc: 'Fighter (EK PHB) — Weapon Bond / War Magic / Eldritch Strike.' },
      { name: 'divinesoul', usage: '!divinesoul', desc: 'Sorcerer — Favored by the Gods: 2d4 to a failed save/attack 1/short.' },
      { name: 'stormsorc', usage: '!stormsorc', desc: 'Sorcerer — Tempestuous Magic: fly 10 ft on L1+ cast (no OA).' },
      { name: 'aberrantmind', usage: '!aberrantmind', desc: 'Sorcerer (TCE) — Telepathic Speech + Psionic Spells; L6 SP → spell.' },
      { name: 'clockwork', usage: '!clockwork', desc: 'Sorcerer (TCE) — Restore Balance reaction: cancel adv/disadv within 60 ft.' },
      { name: 'genielock', usage: '!genielock', desc: "Warlock — Genie's Vessel / Genie's Wrath: once per turn +PB dmg." },
      { name: 'fathomless', usage: '!fathomless [target]', desc: 'Warlock — Tentacle of the Deeps: Xd8+CHA cold, -10 ft speed.' },
      { name: 'undeadlock', usage: '!undeadlock', desc: 'Warlock — Form of Dread: temp HP, frightful aura, PB uses/long rest.' },
      { name: 'circledreams', usage: '!circledreams', desc: 'Druid (Dreams XGE) — Balm of the Summer Court, Hearth of Moonlight.' },
      { name: 'shepherd', usage: '!shepherd', desc: 'Druid (Shepherd XGE) — Spirit Totem (Bear/Hawk/Unicorn).' },
      { name: 'spores', usage: '!spores', desc: 'Druid (Spores TCE) — Halo of Spores + Symbiotic Entity.' },
      { name: 'stars', usage: '!stars', desc: 'Druid (Stars TCE) — Starry Form: Archer / Chalice / Dragon.' },
      { name: 'wildfire', usage: '!wildfire', desc: 'Druid (Wildfire TCE) — Wildfire Spirit companion + Cauterizing Flames.' },
      { name: 'kensei', usage: '!kensei <parry|shot|strike|block>', desc: 'Monk — Agile Parry / Kensei Shot / Deft Strike / Sharpen Blade.' },
      { name: 'mercy', usage: '!mercy <healing|harm>', desc: 'Monk (Mercy TCE) — Hand of Healing or Hand of Harm (1 ki).' },
      { name: 'fourelements', usage: '!fourelements [discipline]', desc: 'Monk (PHB) — Four Elements disciplines reference.' },
      { name: 'creation', usage: '!creation', desc: 'Bard (Creation TCE) — Note of Potential + Performance of Creation.' },
      { name: 'eloquence', usage: '!eloquence', desc: 'Bard (Eloquence TCE) — Silver Tongue + Unsettling Words.' },
      { name: 'spirits', usage: '!spirits', desc: 'Bard (Spirits TCE) — Spiritual Focus + Tales from Beyond.' },
      { name: 'swords', usage: '!swords', desc: 'Bard (Swords XGE) — Bonus proficiencies + Blade Flourish.' },
      { name: 'phantom', usage: '!phantom', desc: 'Rogue (Phantom TCE) — Wails from the Grave: half-SA necrotic to 2nd target.' },
      { name: 'alchemist', usage: '!alchemist', desc: 'Artificer — Alchemist Spells + Experimental Elixir d6+INT.' },
      { name: 'artillerist', usage: '!artillerist', desc: 'Artificer — Eldritch Cannon (Flamethrower/Force Ballista/Protector).' },
      { name: 'battlesmith', usage: '!battlesmith', desc: 'Artificer — Steel Defender companion + Arcane Jolt.' },
      { name: 'armorer', usage: '!armorer', desc: 'Artificer — Armor Model (Guardian / Infiltrator).' },
      { name: 'stormherald', usage: '!stormherald [desert|sea|tundra]', desc: 'Barbarian (Storm Herald XGE) — Storm Aura variants.' },
      { name: 'beastbarb', usage: '!beastbarb [bite|claws|tail]', desc: 'Barbarian (Beast TCE) — Form of the Beast natural weapons.' },
      { name: 'glorypaladin', usage: '!glorypaladin <peerless|inspiring>', desc: 'Paladin (Glory TCE) — Peerless Athlete or 2d8 Inspiring Smite.' },
      { name: 'watchers', usage: '!watchers', desc: 'Paladin (Watchers XGE) — Watcher\'s Will, Abjure the Extraplanar.' },
    ],
  },
  {
    title: 'Hazards: diseases + poisons',
    entries: [
      { name: 'disease', usage: '!disease <slug> <target> | list | help <slug>', desc: 'Apply a disease (sewer-plague, sight-rot, cackle-fever, mindfire, filth-fever); rolls initial save + cadence.' },
      { name: 'poison', usage: '!poison <slug> <target> | list | help <slug>', desc: '14 canonical poisons — drow-poison, wyvern-poison, crawler-mucus, assassins-blood, basic-poison, midnight-tears, pale-tincture, serpent-venom, truth-serum, oil-of-taggit, purple-worm-poison, essence-of-ether, malice, torpor.' },
    ],
  },
  {
    title: 'Environment + variant combat',
    entries: [
      { name: 'underwater', usage: '!underwater on|off', dmOnly: true, desc: 'Toggle aquatic flag + broadcast PHB p.198 ruleset reminder.' },
      { name: 'mount', usage: '!mount <rider> <mount> [controlled|independent]', desc: 'Set up mount relationship (PHB p.198) — half-speed mount/dismount, shared init.' },
      { name: 'dismount', usage: '!dismount <rider>', desc: 'End the mount link (half speed).' },
      { name: 'chase', usage: '!chase [urban|wilderness]', desc: 'Roll XGE chase complication table for the chosen terrain.' },
    ],
  },
  {
    title: 'Downtime + utility',
    entries: [
      { name: 'craft', usage: '!craft <item> <gp> [helpers]', desc: 'Compute crafting days (50 gp/day per crafter) + half-gp material cost.' },
      { name: 'multiclass', usage: '!multiclass <class>', desc: 'Check PHB p.163 multiclass prereqs against caller\'s ability scores.' },
      { name: 'encumbrance', usage: '!encumbrance [lbs]', desc: 'PHB p.176 variant thresholds from STR; optional lbs maps to a status band.' },
      { name: 'currency', usage: '!currency <amt><unit>', desc: 'Convert across cp / sp / ep / gp / pp. E.g. `!currency 150gp`.' },
    ],
  },
  {
    title: 'Racial innate spells + throw',
    entries: [
      { name: 'racial', usage: '!racial [cast] <spell> | list | reset | resetshort', desc: 'Innate race spells (Tiefling Thaumaturgy/Hellish Rebuke/Darkness, Drow Faerie Fire, Aasimar Light, etc.) with per-rest charges.' },
      { name: 'throw', usage: '!throw <weapon> <target>', desc: '5e RAW — thrown weapon lands at target\'s feet (not attacker\'s tile).' },
    ],
  },
  {
    title: 'Meta',
    entries: [
      { name: 'lucky', usage: '!lucky use | status | reset', desc: 'Lucky feat — spend a luck point to roll an extra d20 (3/long rest).' },
    ],
  },
  {
    title: 'Notes',
    entries: [
      { name: 'note', usage: '!note <title> | <body>', desc: 'Post a note visible to the whole party.' },
      { name: 'pcnote', usage: '!pcnote <title> | <body>', desc: 'Note visible only to PCs (not DM).' },
      { name: 'gmnote', usage: '!gmnote <title> | <body>', dmOnly: true, desc: 'DM-only note.' },
    ],
  },
  {
    title: 'Area of effect',
    entries: [
      { name: 'aoe', usage: '!aoe <shape> <size> [color]', dmOnly: true, desc: 'Drop a timed AoE template on the canvas.' },
      { name: 'save', usage: '!save <ability> <dc> <dice>/<type> <target1> [target2 …]', dmOnly: true, desc: 'Resolve a spell save + damage against multiple targets. Half on save.' },
      { name: 'stealth', usage: '!stealth [hide]', desc: 'Roll Stealth vs each visible enemy\'s passive Perception. `hide` auto-applies the badge if you beat them all.' },
    ],
  },
  {
    title: 'Dice',
    entries: [
      { name: 'roll', usage: '/roll <notation>', desc: 'Roll dice (3D physical roll). Alias: /r' },
    ],
  },
];

function formatHelp(isDM: boolean): string {
  const lines: string[] = ['**Chat commands** (case-insensitive):'];
  for (const g of GROUPS) {
    const visible = g.entries.filter((e) => isDM || !e.dmOnly);
    if (visible.length === 0) continue;
    lines.push('');
    lines.push(`__${g.title}__`);
    for (const e of visible) {
      const dmBadge = e.dmOnly ? ' [DM]' : '';
      lines.push(`\`${e.usage}\`${dmBadge} — ${e.desc}`);
    }
  }
  return lines.join('\n');
}

async function handleHelp(c: ChatCommandContext): Promise<boolean> {
  whisperToCaller(c.io, c.ctx, formatHelp(c.ctx.player.role === 'dm'));
  return true;
}

registerChatCommand(['help', 'commands', '?'], handleHelp);
