import type { RuleSource } from '@dnd-vtt/shared';

export interface BackgroundEntry {
  slug: string;
  name: string;
  skills: string[];
  tools?: string[];
  languages?: number;
  feature: string;
  snippet: string;
  description: string;
  /** Absent = PHB. */
  source?: RuleSource;
}

/**
 * 5e PHB backgrounds. Static data. Most of a background's effect is
 * narrative (the RP flavor + optional characteristics) — mechanically
 * they grant 2 skill proficiencies, sometimes tools or languages, and
 * a signature feature.
 */
export const BACKGROUNDS: BackgroundEntry[] = [
  {
    slug: 'acolyte',
    name: 'Acolyte',
    skills: ['Insight', 'Religion'],
    languages: 2,
    feature: 'Shelter of the Faithful',
    snippet: 'Temple-raised. Free lodging at your faith\'s shrines.',
    description: 'You served a temple, mediated the divine, and now walk the world armed with scripture. **Shelter of the Faithful**: you (and your adventuring companions) can expect free healing and care at a temple, shrine, or other established presence of your faith.',
  },
  {
    slug: 'charlatan',
    name: 'Charlatan',
    skills: ['Deception', 'Sleight of Hand'],
    tools: ['Disguise kit', 'Forgery kit'],
    feature: 'False Identity',
    snippet: 'Professional liar. Can forge documents, adopt personas.',
    description: 'You have always had a way with people. **False Identity**: you have created a second identity that includes documentation, established acquaintances, and disguises. You can also forge documents (including official papers and personal letters) as long as you have seen an example.',
  },
  {
    slug: 'criminal',
    name: 'Criminal',
    skills: ['Deception', 'Stealth'],
    tools: ['One gaming set', 'Thieves\' tools'],
    feature: 'Criminal Contact',
    snippet: 'You know a guy. Underworld-connected.',
    description: 'You are an experienced criminal with a history of breaking the law. **Criminal Contact**: you have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You can send messages through a chain of trusted intermediaries.',
  },
  {
    slug: 'entertainer',
    name: 'Entertainer',
    skills: ['Acrobatics', 'Performance'],
    tools: ['Disguise kit', 'One musical instrument'],
    feature: 'By Popular Demand',
    snippet: 'Performer. Free lodging + audience.',
    description: 'You thrive in front of an audience. **By Popular Demand**: you can always find a place to perform — usually an inn or tavern, sometimes a circus. At such a place, you receive free lodging and food of a modest or comfortable standard, and your performances are well-received.',
  },
  {
    slug: 'folk-hero',
    name: 'Folk Hero',
    skills: ['Animal Handling', 'Survival'],
    tools: ['One artisan\'s tools', 'Vehicles (land)'],
    feature: 'Rustic Hospitality',
    snippet: 'Common-folk champion. Commoners shelter you.',
    description: 'You come from a humble social rank, but you are destined for so much more. **Rustic Hospitality**: since you come from the ranks of common folk, you fit in among them with ease. You can find a place to hide, rest, or recuperate among other commoners — they will shield you from the law or anyone else searching for you (but won\'t risk their lives).',
  },
  {
    slug: 'guild-artisan',
    name: 'Guild Artisan',
    skills: ['Insight', 'Persuasion'],
    tools: ['One artisan\'s tools'],
    languages: 1,
    feature: 'Guild Membership',
    snippet: 'Tradesman with guild support and networks.',
    description: 'You are a member of an artisan\'s guild, skilled in a particular field. **Guild Membership**: you can rely on certain benefits that membership provides — fellow guild members provide lodging and food if necessary, and pay for your funeral if needed. You may also gain political influence through the guild.',
  },
  {
    slug: 'hermit',
    name: 'Hermit',
    skills: ['Medicine', 'Religion'],
    tools: ['Herbalism kit'],
    languages: 1,
    feature: 'Discovery',
    snippet: 'Lived in seclusion. Has one unique discovery.',
    description: 'You lived in seclusion for a formative part of your life. **Discovery**: the quiet seclusion of your extended hermitage gave you access to a unique and powerful discovery — a great truth about the cosmos, the overthrow of a ruler, a revelation about a powerful monster, or a secret about a prominent figure.',
  },
  {
    slug: 'noble',
    name: 'Noble',
    skills: ['History', 'Persuasion'],
    tools: ['One gaming set'],
    languages: 1,
    feature: 'Position of Privilege',
    snippet: 'High-born. Opens doors with your title.',
    description: 'You understand wealth, power, and privilege. **Position of Privilege**: thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and people assume you have the right to be wherever you are.',
  },
  {
    slug: 'outlander',
    name: 'Outlander',
    skills: ['Athletics', 'Survival'],
    tools: ['One musical instrument'],
    languages: 1,
    feature: 'Wanderer',
    snippet: 'Wilderness-born. Never lost, always fed.',
    description: 'You grew up in the wilds, far from civilization. **Wanderer**: you have an excellent memory for maps and geography, and you can always recall the general layout of terrain, settlements, and other features around you. In addition, you can find food and fresh water for yourself and up to five other people each day, provided the land offers them.',
  },
  {
    slug: 'sage',
    name: 'Sage',
    skills: ['Arcana', 'History'],
    languages: 2,
    feature: 'Researcher',
    snippet: 'Scholar. Knows where to find any answer.',
    description: 'You spent years learning the lore of the multiverse. **Researcher**: when you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it.',
  },
  {
    slug: 'sailor',
    name: 'Sailor',
    skills: ['Athletics', 'Perception'],
    tools: ['Navigator\'s tools', 'Vehicles (water)'],
    feature: 'Ship\'s Passage',
    snippet: 'Former crew. Free passage on sailing vessels.',
    description: 'You sailed on a seagoing vessel for years. **Ship\'s Passage**: when you need to, you can secure free passage on a sailing ship for yourself and your adventuring companions. You and your companions may have to work during the voyage as part of the crew.',
  },
  {
    slug: 'soldier',
    name: 'Soldier',
    skills: ['Athletics', 'Intimidation'],
    tools: ['One gaming set', 'Vehicles (land)'],
    feature: 'Military Rank',
    snippet: 'Veteran. Rank still carries weight.',
    description: 'War has been your life for as long as you care to remember. **Military Rank**: you have a military rank from your career as a soldier. Soldiers loyal to your former organization still recognize your authority and influence, and they defer to you if they are of a lower rank.',
  },
  {
    slug: 'urchin',
    name: 'Urchin',
    skills: ['Sleight of Hand', 'Stealth'],
    tools: ['Disguise kit', 'Thieves\' tools'],
    feature: 'City Secrets',
    snippet: 'Street kid. Travel half-speed in cities.',
    description: 'You grew up on the streets alone, orphaned and poor. **City Secrets**: you know the secret patterns and flow of cities and can find passages through the urban sprawl that others would miss. When not in combat, you (and companions you lead) can travel between any two locations in the city twice as fast as your speed would normally allow.',
  },

  // --- Xanathar's Guide to Everything ---
  {
    slug: 'city-watch',
    name: 'City Watch',
    skills: ['Athletics', 'Insight'],
    languages: 2,
    feature: 'Watcher\'s Eye',
    snippet: 'Urban law enforcement. Navigate city politics + guards.',
    description: 'You served the city as a guard, investigator, or officer of the watch. **Watcher\'s Eye**: you can easily find the local outpost of the watch, armies, or other law-keeping organization. You can also navigate settlements enough to locate merchants, priests, and officials of any rank.',
    source: 'xge',
  },
  {
    slug: 'clan-crafter',
    name: 'Clan Crafter',
    skills: ['History', 'Insight'],
    tools: ['One artisan\'s tools'],
    languages: 1,
    feature: 'Respect of the Stout Folk',
    snippet: 'Dwarven artisan. Guaranteed welcome in dwarven strongholds.',
    description: 'You were raised in one of the great clans of the dwarves, trained in a craft passed down through generations. **Respect of the Stout Folk**: all dwarves treat you with respect — free lodging, food, a listen in dwarven enclaves.',
    source: 'xge',
  },
  {
    slug: 'cloistered-scholar',
    name: 'Cloistered Scholar',
    skills: ['History', 'One from Arcana/Nature/Religion'],
    languages: 2,
    feature: 'Library Access',
    snippet: 'Library-raised. Library stamp gets you in almost anywhere.',
    description: 'You spent your formative years in the halls of a great library. **Library Access**: though others must often endure lengthy review before being admitted, you have free and easy access to books, scrolls, and restricted collections.',
    source: 'xge',
  },
  {
    slug: 'courtier',
    name: 'Courtier',
    skills: ['Insight', 'Persuasion'],
    languages: 2,
    feature: 'Court Functionary',
    snippet: 'Palace insider. Reads bureaucracy and court gossip.',
    description: 'You served a noble or royal court as an advisor, steward, or herald. **Court Functionary**: your knowledge of the workings of courts gives you access to documents, proceedings, and insights that would otherwise take months to uncover.',
    source: 'xge',
  },
  {
    slug: 'faction-agent',
    name: 'Faction Agent',
    skills: ['Insight', 'One Intelligence/Wisdom/Charisma skill'],
    languages: 2,
    feature: 'Safe Haven',
    snippet: 'Loyal to a cause. Faction members recognize and aid you.',
    description: 'You are an agent of a larger organization — a faction, order, or guild with interests across the realm. **Safe Haven**: your faction maintains safehouses + contacts in most settlements that provide shelter, contact, or information to agents in good standing.',
    source: 'xge',
  },
  {
    slug: 'far-traveler',
    name: 'Far Traveler',
    skills: ['Insight', 'Perception'],
    tools: ['One musical instrument or gaming set'],
    languages: 1,
    feature: 'All Eyes on You',
    snippet: 'Outlander from distant lands. Curiosity opens doors.',
    description: 'You hail from a distant, exotic land — your dress, mannerisms, and speech mark you as a visitor. **All Eyes on You**: you naturally draw the attention of locals who are eager to learn more about you, granting audiences with nobles, merchants, and other leaders who would otherwise be inaccessible.',
    source: 'xge',
  },
  {
    slug: 'inheritor',
    name: 'Inheritor',
    skills: ['Survival', 'One from Arcana/History/Religion'],
    tools: ['One gaming set or musical instrument'],
    languages: 1,
    feature: 'Inheritance',
    snippet: 'Bequeathed a priceless heirloom. Ancestors watch over you.',
    description: 'You inherited an item of evident significance — a weapon, trinket, map, map-fragment, or keepsake. **Inheritance**: your inheritance could help you, haunt you, or both. Choose from a table of options (heirloom weapon, letter, locket, map, sigil, trinket) and describe its significance.',
    source: 'xge',
  },
  {
    slug: 'knight-of-the-order',
    name: 'Knight of the Order',
    skills: ['Persuasion', 'One from Arcana/History/Nature/Religion'],
    tools: ['One gaming set or musical instrument'],
    languages: 1,
    feature: 'Knightly Regard',
    snippet: 'Sworn member of a knightly order. Comrades shelter you.',
    description: 'You are a knight in the service of an order of like-minded knights. **Knightly Regard**: in any settlement where a chapter house or outpost of your order stands, you and your companions can expect free room, board, and perhaps aid.',
    source: 'xge',
  },
  {
    slug: 'mercenary-veteran',
    name: 'Mercenary Veteran',
    skills: ['Athletics', 'Persuasion'],
    tools: ['One gaming set', 'Vehicles (land)'],
    feature: 'Mercenary Life',
    snippet: 'For-hire soldier. Price-checks jobs and contacts.',
    description: 'You led the rough-and-tumble life of a mercenary, answering to gold rather than a lord or cause. **Mercenary Life**: you know the mercenary life inside and out — identify mercenary companies by their emblems, name their leaders, and know the going rate for a job by size and danger.',
    source: 'xge',
  },
  {
    slug: 'urban-bounty-hunter',
    name: 'Urban Bounty Hunter',
    skills: ['Two from Deception/Insight/Persuasion/Stealth'],
    tools: ['Two from gaming sets / musical instruments / thieves\' tools'],
    feature: 'Ear to the Ground',
    snippet: 'Hunts marks in cities. Network of underworld informants.',
    description: 'You track criminals, fugitives, or marks for coin. **Ear to the Ground**: you know the streets, bars, and back rooms of any major city, and you have a network of contacts you can call on for local gossip, rumors, and information.',
    source: 'xge',
  },
  {
    slug: 'uthgardt-tribe-member',
    name: 'Uthgardt Tribe Member',
    skills: ['Athletics', 'Survival'],
    tools: ['One musical instrument or artisan\'s tools'],
    languages: 1,
    feature: 'Uthgardt Heritage',
    snippet: 'Forgotten Realms barbarian tribesman. Clan hospitality.',
    description: 'You grew up in one of the barbarian tribes of the North. **Uthgardt Heritage**: you have an excellent knowledge of the North, and any member of your tribe will provide food, shelter, and passage when asked.',
    source: 'xge',
  },
  {
    slug: 'waterdhavian-noble',
    name: 'Waterdhavian Noble',
    skills: ['History', 'Persuasion'],
    tools: ['One gaming set or musical instrument'],
    languages: 1,
    feature: 'Kept in Style',
    snippet: 'Waterdeep aristocracy. Family stipend of 2 gp/day.',
    description: 'You hail from one of the noble houses of Waterdeep. **Kept in Style**: while in Waterdeep (and any other city where your family has allied houses), you and up to three companions receive free lodging and food at a comfortable inn, and can count on sponsorship of up to **2 gp per day** in incidentals.',
    source: 'xge',
  },

  // --- Curse of Strahd / Ravenloft ---
  {
    slug: 'haunted-one',
    name: 'Haunted One',
    skills: ['Two from Arcana/Investigation/Religion/Survival'],
    languages: 1,
    feature: 'Heart of Darkness',
    snippet: 'Survivor of a horror. Commoners instinctively trust you.',
    description: 'You have encountered an elder evil and survived, but not without cost. **Heart of Darkness**: common folk recognize your haunted demeanor — they do their utmost to help you, offering shelter and food, and even risking their lives for you if needed.',
    source: 'dmg',
  },

  // --- Tomb of Annihilation / exploration ---
  {
    slug: 'anthropologist',
    name: 'Anthropologist',
    skills: ['Insight', 'Religion'],
    languages: 2,
    feature: 'Adept Linguist',
    snippet: 'Studies cultures. Communicates basic concepts without language.',
    description: 'You study societies and customs for a living. **Adept Linguist**: you can communicate basic ideas with creatures that don\'t speak your language. You can also quickly learn the rudiments of a new language by spending a day observing it.',
    source: 'xge',
  },
  {
    slug: 'archaeologist',
    name: 'Archaeologist',
    skills: ['History', 'Survival'],
    tools: ['Cartographer\'s tools or navigator\'s tools'],
    languages: 1,
    feature: 'Dust Digger',
    snippet: 'Ruin-delver. Finds shelter in ancient sites.',
    description: 'You dig and delve in old ruins to recover lost treasure + lore. **Dust Digger**: if you spend at least 1 hour examining an area, you learn the basic history of the site, and have a map of any surviving ruins or structures in the area (if the DM agrees).',
    source: 'xge',
  },

  // --- Tasha's / Wildemount / Witchlight ---
  {
    slug: 'feylost',
    name: 'Feylost',
    skills: ['Deception', 'Survival'],
    tools: ['One musical instrument'],
    languages: 1,
    feature: 'Feywild Connection',
    snippet: 'Spent years in the Feywild. Immunity to being charmed/fear.',
    description: 'You spent part of your life lost in the Feywild, its strange magic still colors your dreams. **Feywild Connection**: reach out mentally to any ally within 1 mile who is also connected to the Feywild. Some see visions of an old fey patron during such visits.',
    source: 'witchlight',
  },
  {
    slug: 'witchlight-hand',
    name: 'Witchlight Hand',
    skills: ['Performance', 'Sleight of Hand'],
    tools: ['Disguise kit', 'One musical instrument'],
    languages: 1,
    feature: 'Carnival Fixture',
    snippet: 'Carnival worker of the Witchlight. Recognized by its members.',
    description: 'You work for the Witchlight Carnival, a traveling wonder that appears in the mortal world once every eight years. **Carnival Fixture**: fellow Witchlight Hands recognize and help you, offering rides, shelter, and news from the Feywild.',
    source: 'witchlight',
  },
  {
    slug: 'grinner',
    name: 'Grinner',
    skills: ['Deception', 'Performance'],
    tools: ['Disguise kit', 'One musical instrument'],
    languages: 2,
    feature: 'Ballad of the Grinning Fool',
    snippet: 'Ruby-tongued spy. Spies posing as wandering bards.',
    description: 'You are one of the Grinning Fools, a Clovis Concord organization of bards working as information-gatherers. **Ballad of the Grinning Fool**: ordinary folk give you a welcoming smile, but those in the know understand your trade — grinners pass information via specific songs and ciphers.',
    source: 'ua',
  },
  {
    slug: 'volstrucker-agent',
    name: 'Volstrucker Agent',
    skills: ['Deception', 'Stealth'],
    languages: 2,
    feature: 'Kryn Dynasty Shadow',
    snippet: 'Clandestine Empire assassin. Drop-points and safehouses.',
    description: 'You are (or were) an agent of the Cerberus Assembly\'s secret order of shadow-agents. **Kryn Dynasty Shadow**: your network has drop-points, safehouses, and coded messengers throughout the Dwendalian Empire.',
    source: 'ua',
  },
];
