export interface ClassEntry {
  slug: string;
  name: string;
  hitDie: number;
  primaryAbility: string;
  savingThrows: string[];
  subclasses: string[];
  snippet: string;
  description: string;
}

/**
 * 5e PHB classes surfaced in the wiki. Static data — level-by-level
 * feature tables are stored separately in `class-features.ts` when
 * that ships; this glossary is the lookup reference players reach for
 * mid-session.
 */
export const CLASSES: ClassEntry[] = [
  {
    slug: 'barbarian',
    name: 'Barbarian',
    hitDie: 12,
    primaryAbility: 'Strength',
    savingThrows: ['Strength', 'Constitution'],
    subclasses: ['Path of the Berserker', 'Path of the Totem Warrior', 'Path of the Zealot (XGE)', 'Path of the Ancestral Guardian (XGE)'],
    snippet: 'd12 HD. Rage, reckless melee, primal fury.',
    description: [
      '**Rage** at level 1: bonus action, advantage on STR checks + saves, +2 damage on melee STR attacks, resistance to bludgeoning / piercing / slashing. Lasts 1 minute or until you go a turn without attacking / taking damage.',
      '**Unarmored Defense**: AC = 10 + DEX + CON when not wearing armor.',
      '**Reckless Attack** (L2): advantage on melee STR attacks this turn, but attacks against you have advantage.',
      '**Danger Sense** (L2): advantage on DEX saves vs effects you can see.',
      '**Extra Attack** (L5), **Fast Movement** (L5, +10 ft unarmored), **Feral Instinct** (L7 adv on init), **Brutal Critical** (L9), **Relentless Rage** (L11), **Persistent Rage** (L15), **Indomitable Might** (L18), **Primal Champion** (L20 +4 STR + CON).',
    ].join('\n\n'),
  },
  {
    slug: 'bard',
    name: 'Bard',
    hitDie: 8,
    primaryAbility: 'Charisma',
    savingThrows: ['Dexterity', 'Charisma'],
    subclasses: ['College of Lore', 'College of Valor', 'College of Glamour (XGE)', 'College of Swords (XGE)', 'College of Whispers (XGE)'],
    snippet: 'd8 HD. Full caster (CHA). Inspiration, Jack of All Trades.',
    description: [
      '**Spellcasting** (CHA): full caster, spells known list, ritual tag castable.',
      '**Bardic Inspiration** (L1): bonus action, d6/d8/d10/d12 at levels 1/5/10/15. Ally adds it to one attack/check/save within 10 minutes. Uses = CHA mod, recharge short rest (long rest pre-L5).',
      '**Jack of All Trades** (L2): half proficiency on ability checks you\'re not proficient in.',
      '**Song of Rest** (L2): during short rest, allies who spend hit dice regain extra HP.',
      '**Expertise** (L3 + L10): double proficiency on two skills at each level.',
      '**Font of Inspiration** (L5): BI recharges on short rest.',
      '**Countercharm** (L6): action to give allies within 30 ft advantage on saves vs frightened / charmed.',
      '**Magical Secrets** (L10/14/18): learn 2 spells from ANY class list.',
    ].join('\n\n'),
  },
  {
    slug: 'cleric',
    name: 'Cleric',
    hitDie: 8,
    primaryAbility: 'Wisdom',
    savingThrows: ['Wisdom', 'Charisma'],
    subclasses: ['Knowledge', 'Life', 'Light', 'Nature', 'Tempest', 'Trickery', 'War', 'Death (DMG)', 'Forge (XGE)', 'Grave (XGE)', 'Order (TCE)', 'Peace (TCE)', 'Twilight (TCE)'],
    snippet: 'd8 HD. Full caster (WIS). Channel Divinity, domain spells.',
    description: [
      '**Spellcasting** (WIS): full caster, prepared spells = WIS mod + cleric level.',
      '**Divine Domain** (L1): subclass picks your flavor; grants domain spells always prepared + level-1 feature.',
      '**Channel Divinity** (L2): limited-use domain power; starts with Turn Undead. Recharges short rest. Uses = 1 (L2), 2 (L6), 3 (L18).',
      '**Destroy Undead** (L5+, increasingly potent): low-CR undead fail the turn save and are destroyed outright.',
      '**Divine Intervention** (L10): 1% × cleric level chance the god answers; always works at L20.',
    ].join('\n\n'),
  },
  {
    slug: 'druid',
    name: 'Druid',
    hitDie: 8,
    primaryAbility: 'Wisdom',
    savingThrows: ['Intelligence', 'Wisdom'],
    subclasses: ['Circle of the Land', 'Circle of the Moon', 'Circle of Dreams (XGE)', 'Circle of the Shepherd (XGE)', 'Circle of Spores (TCE)', 'Circle of Stars (TCE)', 'Circle of Wildfire (TCE)'],
    snippet: 'd8 HD. Full caster (WIS). Wild Shape.',
    description: [
      '**Spellcasting** (WIS): full caster, prepared spells = WIS mod + druid level.',
      '**Druidic** (L1): secret druid-only language.',
      '**Wild Shape** (L2): transform into a beast you\'ve seen. Twice per short rest. CR / swim / fly limits scale with level.',
      '**Druid Circle** (L2): subclass — Land gets bonus spells + Natural Recovery; Moon\'s wild shape CR scales aggressively + can do combat wild shape as bonus action.',
      '**Timeless Body** (L18), **Beast Spells** (L18), **Archdruid** (L20: unlimited wild shape).',
    ].join('\n\n'),
  },
  {
    slug: 'fighter',
    name: 'Fighter',
    hitDie: 10,
    primaryAbility: 'Strength or Dexterity',
    savingThrows: ['Strength', 'Constitution'],
    subclasses: ['Champion', 'Battle Master', 'Eldritch Knight', 'Arcane Archer (XGE)', 'Cavalier (XGE)', 'Samurai (XGE)', 'Psi Warrior (TCE)', 'Rune Knight (TCE)'],
    snippet: 'd10 HD. Second Wind, Action Surge, Extra Attack (up to 4).',
    description: [
      '**Fighting Style** (L1): Archery (+2 ranged), Defense (+1 AC w/ armor), Dueling (+2 dmg one-hand), Great Weapon Fighting (reroll 1s/2s on 2-h), Protection (reaction impose disadv), Two-Weapon Fighting (add mod to off-hand), and more from later books.',
      '**Second Wind** (L1): bonus action, heal 1d10 + fighter level. Short rest recharge.',
      '**Action Surge** (L2): 1 extra action on your turn. Short rest. 2 uses at L17.',
      '**Martial Archetype** (L3): subclass features.',
      '**Extra Attack** (L5/11/20): 2 → 3 → 4 attacks per Attack action.',
      '**Indomitable** (L9/13/17): reroll a failed save; 1 → 2 → 3 uses per long rest.',
    ].join('\n\n'),
  },
  {
    slug: 'monk',
    name: 'Monk',
    hitDie: 8,
    primaryAbility: 'Dexterity + Wisdom',
    savingThrows: ['Strength', 'Dexterity'],
    subclasses: ['Way of the Open Hand', 'Way of Shadow', 'Way of the Four Elements', 'Way of the Long Death (XGE)', 'Way of the Sun Soul (XGE)', 'Way of Mercy (TCE)', 'Way of the Astral Self (TCE)'],
    snippet: 'd8 HD. Unarmored Defense + Movement, Ki, Martial Arts.',
    description: [
      '**Unarmored Defense**: AC = 10 + DEX + WIS (no armor / shield).',
      '**Martial Arts** (L1): unarmed + monk weapons use DEX, die 1d4 → 1d6 → 1d8 → 1d10 at L5/11/17. Extra unarmed strike as bonus action.',
      '**Ki** (L2): pool = monk level. Recharge short rest. Spend for **Flurry of Blows** (2 extra unarmed strikes bonus action), **Patient Defense** (dodge as bonus action), **Step of the Wind** (dash/disengage bonus action + double jump).',
      '**Unarmored Movement** (L2+): +10 ft, +15 at L6, etc., with vertical-surface / water-walking at higher levels.',
      '**Deflect Missiles** (L3) • **Slow Fall** (L4) • **Extra Attack** (L5) • **Stunning Strike** (L5, spend 1 ki on hit → CON save or stunned) • **Ki-Empowered Strikes** (L6 magical) • **Stillness of Mind** (L7) • **Evasion** (L7) • **Purity of Body** (L10) • **Tongue of the Sun and Moon** (L13) • **Diamond Soul** (L14 prof in all saves) • **Timeless Body** (L15) • **Empty Body** (L18) • **Perfect Self** (L20 min 4 ki).',
    ].join('\n\n'),
  },
  {
    slug: 'paladin',
    name: 'Paladin',
    hitDie: 10,
    primaryAbility: 'Strength + Charisma',
    savingThrows: ['Wisdom', 'Charisma'],
    subclasses: ['Oath of Devotion', 'Oath of the Ancients', 'Oath of Vengeance', 'Oathbreaker (DMG)', 'Oath of Conquest (XGE)', 'Oath of Redemption (XGE)', 'Oath of Glory (TCE)', 'Oath of the Watchers (TCE)'],
    snippet: 'd10 HD. Half caster (CHA). Lay on Hands, Divine Smite.',
    description: [
      '**Divine Sense** (L1): action to detect celestial / fiend / undead within 60 ft.',
      '**Lay on Hands** (L1): pool = paladin × 5 HP. Restore HP or cure poison/disease.',
      '**Fighting Style** (L2).',
      '**Spellcasting** (L2, CHA): half caster.',
      '**Divine Smite** (L2): when you hit with a melee weapon attack, spend a slot for +2d8 radiant damage (+1d8 per slot level above 1; +1d8 vs undead / fiends).',
      '**Divine Health** (L3): immune to disease.',
      '**Sacred Oath** (L3): subclass features + oath spells.',
      '**Extra Attack** (L5). **Aura of Protection** (L6, +CHA mod to saves within 10 ft). **Aura of Courage** (L10 immune frightened). **Improved Divine Smite** (L11, +1d8 radiant to melee weapon hits). **Cleansing Touch** (L14, action end a spell on a willing target).',
    ].join('\n\n'),
  },
  {
    slug: 'ranger',
    name: 'Ranger',
    hitDie: 10,
    primaryAbility: 'Dexterity + Wisdom',
    savingThrows: ['Strength', 'Dexterity'],
    subclasses: ['Hunter', 'Beast Master', 'Gloom Stalker (XGE)', 'Horizon Walker (XGE)', 'Monster Slayer (XGE)', 'Fey Wanderer (TCE)', 'Swarmkeeper (TCE)', 'Drakewarden (FTD)'],
    snippet: 'd10 HD. Half caster (WIS). Favored Enemy, Natural Explorer.',
    description: [
      '**Favored Enemy** (L1): pick a creature type, advantage on survival tracking + INT checks to recall.',
      '**Natural Explorer** (L1): pick terrain; travel perks + hide in plain sight benefits.',
      '**Fighting Style** (L2).',
      '**Spellcasting** (L2, WIS): half caster.',
      '**Ranger Archetype** (L3): Hunter picks Colossus Slayer / Giant Killer / Horde Breaker. Beast Master gets a companion.',
      '**Primeval Awareness** (L3), **Extra Attack** (L5), **Land\'s Stride** (L8), **Hide in Plain Sight** (L10), **Vanish** (L14), **Feral Senses** (L18), **Foe Slayer** (L20).',
      'Tasha\'s Optional Class Features replace Favored Enemy / Natural Explorer with Favored Foe / Deft Explorer for most groups.',
    ].join('\n\n'),
  },
  {
    slug: 'rogue',
    name: 'Rogue',
    hitDie: 8,
    primaryAbility: 'Dexterity',
    savingThrows: ['Dexterity', 'Intelligence'],
    subclasses: ['Thief', 'Assassin', 'Arcane Trickster', 'Inquisitive (XGE)', 'Mastermind (XGE)', 'Scout (XGE)', 'Swashbuckler (XGE)', 'Phantom (TCE)', 'Soulknife (TCE)'],
    snippet: 'd8 HD. Sneak Attack, Cunning Action, Expertise.',
    description: [
      '**Expertise** (L1 + L6): double proficiency on 2 chosen skills per tier.',
      '**Sneak Attack** (L1): 1d6 extra damage when you hit with a finesse / ranged weapon AND either have advantage OR an ally of the target is within 5 ft of the target. Once per TURN (not round). Scales +1d6 every other level → 10d6 at L19.',
      '**Thieves\' Cant** (L1).',
      '**Cunning Action** (L2): bonus action to **Dash**, **Disengage**, or **Hide**.',
      '**Uncanny Dodge** (L5): reaction, halve damage from one attacker you can see.',
      '**Evasion** (L7): DEX save for half → no damage on success, half on fail.',
      '**Reliable Talent** (L11): any skill check you\'re proficient in treats d20 <10 as 10.',
      '**Blindsense** (L14), **Slippery Mind** (L15, WIS save prof), **Elusive** (L18 no advantage on attacks vs you while not incapacitated), **Stroke of Luck** (L20 once per rest: turn a miss into hit or a failed check into 20).',
    ].join('\n\n'),
  },
  {
    slug: 'sorcerer',
    name: 'Sorcerer',
    hitDie: 6,
    primaryAbility: 'Charisma',
    savingThrows: ['Constitution', 'Charisma'],
    subclasses: ['Draconic Bloodline', 'Wild Magic', 'Divine Soul (XGE)', 'Shadow Magic (XGE)', 'Storm Sorcery (XGE)', 'Aberrant Mind (TCE)', 'Clockwork Soul (TCE)'],
    snippet: 'd6 HD. Full caster (CHA). Metamagic, Font of Magic.',
    description: [
      '**Spellcasting** (CHA): full caster, spells known (not prepared).',
      '**Sorcerous Origin** (L1): subclass — Draconic gets elemental damage + scales + HP bump.',
      '**Font of Magic** (L2): sorcery points = sorcerer level, recharge long rest. Convert slots ↔ sorcery points via Flexible Casting.',
      '**Metamagic** (L3): spend SP to modify spells: Careful (ally exempt from save), Distant (double range), Empowered (reroll 1s/2s), Extended (double duration), Heightened (target disadv on save), Quickened (bonus action cast), Subtle (no V/S components), Twinned (target two creatures with single-target spells).',
      '**Sorcerous Restoration** (L20, regain 4 SP on short rest).',
    ].join('\n\n'),
  },
  {
    slug: 'warlock',
    name: 'Warlock',
    hitDie: 8,
    primaryAbility: 'Charisma',
    savingThrows: ['Wisdom', 'Charisma'],
    subclasses: ['The Archfey', 'The Fiend', 'The Great Old One', 'The Celestial (XGE)', 'The Hexblade (XGE)', 'The Undying (SCAG)', 'The Fathomless (TCE)', 'The Genie (TCE)'],
    snippet: 'd8 HD. Pact caster (CHA). Invocations, Pact Boon.',
    description: [
      '**Otherworldly Patron** (L1): subclass granting features at L1/6/10/14.',
      '**Pact Magic** (L1): very few slots BUT they\'re the highest level you can cast, and recharge on SHORT rests (1/2/2/3/3/4 slots, level 1/1/2/2/3/3 → 5 with L17).',
      '**Eldritch Invocations** (L2+): build-your-own warlock. Start with 2, add 1 at L5/7/9/12/15/18. Prerequisites vary (some need Pact of the Blade, others a specific level).',
      '**Pact Boon** (L3): Chain (find familiar pseudodragon / imp / etc.), Blade (summon weapon as action, bond it), Tome (ritual book with 3 cantrips), Talisman (TCE — ally touching it +d4 on checks).',
      '**Mystic Arcanum** (L11/13/15/17): one named spell of level 6/7/8/9, cast once per long rest, NOT using pact slots.',
      '**Eldritch Master** (L20): regain all pact slots on a 1-minute action (once per long rest).',
    ].join('\n\n'),
  },
  {
    slug: 'wizard',
    name: 'Wizard',
    hitDie: 6,
    primaryAbility: 'Intelligence',
    savingThrows: ['Intelligence', 'Wisdom'],
    subclasses: ['Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation', 'War Magic (XGE)', 'Bladesinging (TCE)', 'Chronurgy (EGW)', 'Graviturgy (EGW)', 'Order of Scribes (TCE)'],
    snippet: 'd6 HD. Full caster (INT). Spellbook + Arcane Recovery.',
    description: [
      '**Spellcasting** (INT): full caster, prepare from spellbook (INT + wizard level spells). Cantrips always prepared.',
      '**Arcane Recovery** (L1): during a short rest, recover slots totaling up to half your wizard level (rounded up), none higher than 5th.',
      '**Arcane Tradition** (L2): subclass — Evocation\'s Sculpt Spells lets allies auto-save for no damage; Abjuration\'s Arcane Ward soaks damage; Divination\'s Portent replaces d20 rolls with rolled numbers kept for the day.',
      '**Spell Mastery** (L18): one 1st and one 2nd level spell castable at will without a slot.',
      '**Signature Spells** (L20): one 3rd-level spell per short rest without a slot.',
    ].join('\n\n'),
  },
  {
    slug: 'artificer',
    name: 'Artificer',
    hitDie: 8,
    primaryAbility: 'Intelligence',
    savingThrows: ['Constitution', 'Intelligence'],
    subclasses: ['Alchemist', 'Artillerist', 'Battle Smith', 'Armorer (TCE)'],
    snippet: 'd8 HD. Half caster (INT). Infuse Item, spell storing.',
    description: [
      '**Magical Tinkering** (L1): touch a tiny object and imbue it with a minor effect (light, message, sound).',
      '**Spellcasting** (L1, INT): half caster — prep spells = INT + half level. Needs a tool focus.',
      '**Infuse Item** (L2): long rest, pick infusions (from a known list that grows) and apply to items — grants +1 bonuses, replicate magic items, etc.',
      '**Specialist** (L3): subclass gives specific spell lists + features.',
      '**The Right Tool for the Job** (L3): 1h, create a set of artisan\'s tools.',
      '**Tool Expertise** (L6), **Flash of Genius** (L7 reaction +INT to ally save/check), **Magic Item Adept/Savant/Master** (scaling infusion slots + attunement cap), **Soul of Artifice** (L20 +1 save per attunement, 1-shot infusion to pop from 0 HP to 1).',
    ].join('\n\n'),
  },
];
