import type { RuleSource } from '@dnd-vtt/shared';

export interface RaceEntry {
  slug: string;
  name: string;
  size: 'Small' | 'Medium' | 'Large' | 'Small or Medium';
  speed: number;
  asi: string;
  subraces: string[];
  snippet: string;
  description: string;
  /** Absent = PHB. */
  source?: RuleSource;
}

/**
 * 5e PHB player species (races). Static reference — mechanical
 * enforcement of traits (darkvision, innate spells, etc.) hooks into
 * the rules engine as each race handler lands.
 */
export const RACES: RaceEntry[] = [
  {
    slug: 'human',
    name: 'Human',
    size: 'Medium',
    speed: 30,
    asi: '+1 to all six ability scores (standard) — or +1 to two + skill + feat (variant)',
    subraces: ['Standard', 'Variant (with feat at L1)'],
    snippet: 'Adaptable, ambitious, ubiquitous.',
    description: 'Most common race. Standard humans get +1 to every ability score. Variant humans (PHB optional rule, most groups use it) swap that for +1 to two abilities, one extra skill proficiency, and one feat at level 1.',
  },
  {
    slug: 'elf',
    name: 'Elf',
    size: 'Medium',
    speed: 30,
    asi: '+2 DEX; subrace adds more',
    subraces: ['High Elf (+1 INT)', 'Wood Elf (+1 WIS)', 'Drow / Dark Elf (+1 CHA)', 'Eladrin (SCAG — +1 INT or CHA)'],
    snippet: '60 ft darkvision. Keen Senses. Fey Ancestry.',
    description: '**Darkvision 60 ft.** **Keen Senses**: proficiency in Perception. **Fey Ancestry**: advantage on saves vs. charmed, magic can\'t put you to sleep. **Trance**: 4h meditation instead of 8h sleep. Subrace features: **High Elf** picks a wizard cantrip + 1 language + longsword/longbow/shortsword/shortbow proficiency. **Wood Elf** gets 35 ft speed + Mask of the Wild. **Drow** gets Superior Darkvision (120 ft) + faerie fire / darkness innate spells at levels 3/5.',
  },
  {
    slug: 'dwarf',
    name: 'Dwarf',
    size: 'Medium',
    speed: 25,
    asi: '+2 CON; subrace adds more',
    subraces: ['Hill Dwarf (+1 WIS)', 'Mountain Dwarf (+2 STR)', 'Duergar (SCAG — +1 STR, invisibility spells)'],
    snippet: '60 ft darkvision. Resilience (adv + resistance to poison).',
    description: '**Darkvision 60 ft.** **Dwarven Resilience**: advantage on saves vs. poison, resistance to poison damage. **Dwarven Combat Training**: battleaxe, handaxe, light hammer, warhammer proficiency. **Stonecunning**: double proficiency on History checks about stonework. Subraces: **Hill Dwarf** adds +1 HP per level (Dwarven Toughness). **Mountain Dwarf** gets light + medium armor proficiency.',
  },
  {
    slug: 'halfling',
    name: 'Halfling',
    size: 'Small',
    speed: 25,
    asi: '+2 DEX; subrace adds more',
    subraces: ['Lightfoot Halfling (+1 CHA)', 'Stout Halfling (+1 CON)'],
    snippet: 'Lucky (reroll nat 1). Brave (adv vs fear). Small.',
    description: '**Lucky**: when you roll a 1 on an attack, ability check, or save, reroll and must use the new roll. **Brave**: advantage on saves vs. frightened. **Halfling Nimbleness**: move through the space of any creature of a size larger than yours. **Lightfoot**: Naturally Stealthy — hide behind a creature one size larger. **Stout**: dwarf-like poison resistance (adv on saves vs. poison + damage resistance).',
  },
  {
    slug: 'dragonborn',
    name: 'Dragonborn',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 CHA',
    subraces: ['Black (acid)', 'Blue (lightning)', 'Brass (fire)', 'Bronze (lightning)', 'Copper (acid)', 'Gold (fire)', 'Green (poison)', 'Red (fire)', 'Silver (cold)', 'White (cold)'],
    snippet: 'Breath weapon once per short rest + damage resistance.',
    description: 'Pick a **Draconic Ancestry** — determines your breath weapon damage type + shape (line or cone) + resistance. **Breath Weapon**: action, DEX or CON save (DC = 8 + CON mod + prof). 2d6 / 3d6 / 4d6 / 5d6 damage scaling at L1/6/11/16. Recharges on short or long rest. **Damage Resistance**: same type as your breath weapon.',
  },
  {
    slug: 'gnome',
    name: 'Gnome',
    size: 'Small',
    speed: 25,
    asi: '+2 INT; subrace adds more',
    subraces: ['Forest Gnome (+1 DEX)', 'Rock Gnome (+1 CON)', 'Deep Gnome / Svirfneblin (SCAG — +1 DEX)'],
    snippet: '60 ft darkvision. Gnome Cunning (adv on INT/WIS/CHA magic saves).',
    description: '**Darkvision 60 ft.** **Gnome Cunning**: advantage on INT, WIS, and CHA saving throws against magic. Subraces: **Forest Gnome** gets Speak with Small Beasts + Minor Illusion cantrip. **Rock Gnome** gets Artificer\'s Lore (double proficiency on magical / alchemical / technological lore) + Tinker (crafting minor clockwork toys).',
  },
  {
    slug: 'half-elf',
    name: 'Half-Elf',
    size: 'Medium',
    speed: 30,
    asi: '+2 CHA, +1 to two other abilities',
    subraces: ['Standard'],
    snippet: '60 ft darkvision. Fey Ancestry. 2 skill proficiencies.',
    description: '**Darkvision 60 ft.** **Fey Ancestry**: advantage on saves vs. charmed, immune to magical sleep. **Skill Versatility**: proficiency in 2 skills of your choice. **Extra Language**.',
  },
  {
    slug: 'half-orc',
    name: 'Half-Orc',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 CON',
    subraces: ['Standard'],
    snippet: '60 ft darkvision. Relentless Endurance (drop to 1 HP once/long rest).',
    description: '**Darkvision 60 ft.** **Menacing**: proficient in Intimidation. **Relentless Endurance**: when reduced to 0 HP but not killed outright, drop to 1 HP instead (once per long rest). **Savage Attacks**: when you score a critical hit with a melee weapon attack, roll one additional weapon damage die.',
  },
  {
    slug: 'tiefling',
    name: 'Tiefling',
    size: 'Medium',
    speed: 30,
    asi: '+2 CHA, +1 INT',
    subraces: ['Asmodeus (PHB default)', 'Baalzebul (MToF)', 'Dispater (MToF)', 'Fierna (MToF)', 'Glasya (MToF)', 'Levistus (MToF)', 'Mammon (MToF)', 'Mephistopheles (MToF)', 'Zariel (MToF)'],
    snippet: '60 ft darkvision. Fire resistance. Innate spells (Thaumaturgy + Hellish Rebuke + Darkness).',
    description: '**Darkvision 60 ft.** **Hellish Resistance**: damage resistance to fire. **Infernal Legacy**: Thaumaturgy cantrip at L1, Hellish Rebuke once per long rest at L3, Darkness once per long rest at L5. Casting ability is Charisma.',
  },
  // ── Elemental Evil Player's Companion / EEPC-origin races ────
  {
    slug: 'aarakocra',
    name: 'Aarakocra',
    size: 'Medium',
    speed: 25,
    asi: '+2 DEX, +1 WIS',
    subraces: [],
    snippet: 'Fly 50 ft. Talon unarmed strike. Auran.',
    description: '**Flight**: 50 ft flying speed (no armor heavier than medium). **Talons**: unarmed strike 1d4 slashing. Speak **Auran**. Setting: elemental planes + Chult jungles. Balance concern at low levels — many DMs ban until tier 2.',
    source: 'eepc',
  },
  {
    slug: 'genasi-air',
    name: 'Genasi (Air)',
    size: 'Medium',
    speed: 30,
    asi: '+2 CON, +1 DEX',
    subraces: ['Air'],
    snippet: 'Unending breath. Hold breath indefinitely. Levitate at L3.',
    description: '**Unending Breath**: hold breath indefinitely. **Mingle with the Wind**: cast **Levitate** once per long rest, no components (CON). Air Genasi are sky-touched mortals with elemental heritage.',
    source: 'eepc',
  },
  {
    slug: 'genasi-earth',
    name: 'Genasi (Earth)',
    size: 'Medium',
    speed: 30,
    asi: '+2 CON, +1 STR',
    subraces: ['Earth'],
    snippet: 'Earth Walk (stone/earth difficult terrain free). Pass Without Trace at L3.',
    description: '**Earth Walk**: move across difficult terrain made of earth/stone without extra movement cost. **Merge with Stone**: cast **Pass Without Trace** once per long rest (CON).',
    source: 'eepc',
  },
  {
    slug: 'genasi-fire',
    name: 'Genasi (Fire)',
    size: 'Medium',
    speed: 30,
    asi: '+2 CON, +1 INT',
    subraces: ['Fire'],
    snippet: '60 ft darkvision. Fire resistance. Produce Flame / Burning Hands.',
    description: '**Darkvision 60 ft.** **Fire Resistance**. **Reach to the Blaze**: Produce Flame cantrip at L1, cast Burning Hands once per long rest at L3 (CON).',
    source: 'eepc',
  },
  {
    slug: 'genasi-water',
    name: 'Genasi (Water)',
    size: 'Medium',
    speed: 30,
    asi: '+2 CON, +1 WIS',
    subraces: ['Water'],
    snippet: 'Swim 30 ft. Amphibious. Acid resistance. Shape Water / Create or Destroy Water.',
    description: '**Swim speed 30 ft + amphibious** (breathe air + water). **Acid Resistance**. **Call to the Wave**: Shape Water cantrip, Create or Destroy Water once per long rest (CON).',
    source: 'eepc',
  },
  {
    slug: 'goliath',
    name: 'Goliath',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 CON',
    subraces: [],
    snippet: 'Stone\'s Endurance reaction (reduce dmg by 1d12+CON). Cold resistance. Mountain Born.',
    description: '**Stone\'s Endurance**: reaction when damaged — reduce by 1d12 + CON mod. 1/short rest. **Powerful Build**: count as one size larger for carrying capacity. **Mountain Born**: cold resistance + acclimated to high altitude. Born of the highest peaks.',
    source: 'eepc',
  },
  // ── Volo's Guide to Monsters / monstrous races ───────────────
  {
    slug: 'aasimar',
    name: 'Aasimar',
    size: 'Medium',
    speed: 30,
    asi: '+2 CHA; subrace adds more',
    subraces: ['Protector (+1 WIS — flight burst + radiant dmg)', 'Scourge (+1 CON — aura deals radiant dmg to enemies)', 'Fallen (+1 STR — necrotic radiance, frightens enemies)'],
    snippet: '60 ft darkvision. Healing Hands (1/long rest). Light cantrip. Celestial Revelation at L3.',
    description: '**Darkvision 60 ft.** **Celestial Resistance**: resistance to necrotic + radiant damage. **Healing Hands**: heal level × 1 HP, 1/long rest. **Light cantrip**. **Celestial Revelation at L3**: bonus action transform for 1 min, radiant damage aura + subrace extras (Protector flies, Scourge pulses radiant dmg, Fallen dims as necrotic fear). Touched by the Upper Planes.',
    source: 'volos',
  },
  {
    slug: 'firbolg',
    name: 'Firbolg',
    size: 'Medium',
    speed: 30,
    asi: '+2 WIS, +1 STR',
    subraces: [],
    snippet: 'Firbolg Magic (Detect Magic / Disguise Self). Hidden Step (bonus action invisibility).',
    description: '**Firbolg Magic**: Detect Magic + Disguise Self, each 1/short rest (WIS). **Hidden Step**: bonus action turn invisible until start of next turn (1/short rest). **Powerful Build**: +size for carrying. **Speech of Beast and Leaf**: limited communication with beasts + plants. Giant-kin druids of the deep forest.',
    source: 'volos',
  },
  {
    slug: 'kenku',
    name: 'Kenku',
    size: 'Medium',
    speed: 30,
    asi: '+2 DEX, +1 WIS',
    subraces: [],
    snippet: 'Mimicry (perfect sound mimicry). Two skill proficiencies.',
    description: '**Expert Forgery**: duplicate existing handwriting + craftsmanship. **Kenku Training**: proficiency in two of Acrobatics, Deception, Stealth, Sleight of Hand. **Mimicry**: perfectly mimic sounds you\'ve heard. Flightless raven-folk cursed to speak only in borrowed phrases.',
    source: 'volos',
  },
  {
    slug: 'lizardfolk',
    name: 'Lizardfolk',
    size: 'Medium',
    speed: 30,
    asi: '+2 CON, +1 WIS',
    subraces: [],
    snippet: 'Natural armor 13+DEX. Bite 1d6 piercing. Swim 30 ft. Hungry Jaws.',
    description: '**Bite**: 1d6 piercing unarmed + gain temp HP = prof bonus after landing. **Cunning Artisan**: craft shields/weapons/armor from corpses. **Hold Breath 15 min**. **Natural Armor**: 13 + DEX (no shield). **Hungry Jaws**: bonus-action bite + temp HP, 1/short rest. **Swim 30 ft.** Cold-blooded swamp predators.',
    source: 'volos',
  },
  {
    slug: 'tabaxi',
    name: 'Tabaxi',
    size: 'Medium',
    speed: 30,
    asi: '+2 DEX, +1 CHA',
    subraces: [],
    snippet: 'Feline Agility (double speed once/turn). Climb 20 ft. Cat claws.',
    description: '**Darkvision 60 ft.** **Feline Agility**: double speed until you stand still — refresh by not moving on a turn. **Cat\'s Claws**: 20 ft climbing speed + unarmed strike 1d4 slashing. **Cat\'s Talent**: proficiency in Perception + Stealth. Jaguar-folk wanderers of distant shores.',
    source: 'volos',
  },
  {
    slug: 'triton',
    name: 'Triton',
    size: 'Medium',
    speed: 30,
    asi: '+1 STR, +1 CON, +1 CHA',
    subraces: [],
    snippet: 'Swim 30 ft. Amphibious. Cold resistance. Fog Cloud / Gust of Wind / Wall of Water.',
    description: '**Amphibious** (breathe air + water). **Control Air and Water**: Fog Cloud at L1, Gust of Wind at L3, Wall of Water at L5 — each 1/long rest. **Emissary of the Sea**: limited speech with water-breathing beasts. **Guardians of the Depths**: cold resistance. **Swim 30 ft.** Protectors of the deep oceans.',
    source: 'volos',
  },
  {
    slug: 'yuan-ti-pureblood',
    name: 'Yuan-Ti Pureblood',
    size: 'Medium',
    speed: 30,
    asi: '+2 CHA, +1 INT',
    subraces: [],
    snippet: '60 ft darkvision. Magic Resistance (adv on all magic saves). Poison immunity.',
    description: '**Darkvision 60 ft.** **Innate Spellcasting**: Poison Spray cantrip, Animal Friendship (vs snakes only) at will, Suggestion 1/long rest at L3 (CHA). **Magic Resistance**: advantage on saving throws vs. spells and magical effects. **Poison Immunity**. Strongest racial in PHB-era 5e by consensus.',
    source: 'volos',
  },
  {
    slug: 'bugbear',
    name: 'Bugbear',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 DEX',
    subraces: [],
    snippet: '60 ft darkvision. Long-Limbed (+5 ft reach first atk). Surprise Attack (+2d6).',
    description: '**Darkvision 60 ft.** **Long-Limbed**: reach +5 ft on attacks made as part of Attack action on your turn. **Powerful Build**: +size for carrying. **Sneaky**: proficiency in Stealth. **Surprise Attack**: deal +2d6 damage to creatures that haven\'t acted yet in combat. Goblinoid brutes with surprising subtlety.',
    source: 'volos',
  },
  {
    slug: 'goblin',
    name: 'Goblin',
    size: 'Small',
    speed: 30,
    asi: '+2 DEX, +1 CON',
    subraces: [],
    snippet: '60 ft darkvision. Fury of the Small (+level dmg). Nimble Escape (Disengage/Hide BA).',
    description: '**Darkvision 60 ft.** **Fury of the Small**: +level damage when hitting a larger creature (1/short rest). **Nimble Escape**: take the Disengage OR Hide action as a bonus action. Volatile, cunning, and survivors above all.',
    source: 'volos',
  },
  {
    slug: 'hobgoblin',
    name: 'Hobgoblin',
    size: 'Medium',
    speed: 30,
    asi: '+2 CON, +1 INT',
    subraces: [],
    snippet: '60 ft darkvision. Martial Training (2 weapons + light armor). Saving Face (+ adjacent allies to roll).',
    description: '**Darkvision 60 ft.** **Martial Training**: proficiency in 2 martial weapons + light armor. **Saving Face**: reaction — add +1 per ally within 30 ft (max +5) to a failed attack/check/save, 1/short rest. Disciplined goblinoid legionaries.',
    source: 'volos',
  },
  {
    slug: 'kobold',
    name: 'Kobold',
    size: 'Small',
    speed: 30,
    asi: '+2 DEX, -2 STR (original) / +2 DEX, +1 CON (MPMM)',
    subraces: [],
    snippet: '60 ft darkvision. Pack Tactics. Sunlight Sensitivity. Grovel, Cower, Beg reaction.',
    description: '**Darkvision 60 ft.** **Pack Tactics**: advantage on attacks when an ally is within 5 ft of the target. **Sunlight Sensitivity**: disadvantage on attack rolls + Perception checks in direct sunlight. **Grovel, Cower, and Beg**: action — all enemies within 10 ft have advantage vs. allies for 1 round (1/short rest). Draconic trap-artisans.',
    source: 'volos',
  },
  {
    slug: 'orc',
    name: 'Orc',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 CON (original) / +2 any, +1 any (MPMM)',
    subraces: [],
    snippet: '60 ft darkvision. Aggressive (bonus-action Dash toward enemy). Powerful Build.',
    description: '**Darkvision 60 ft.** **Aggressive**: bonus action to move up to your speed toward an enemy you can see. **Powerful Build**: +size for carrying. **Primal Intuition** (MPMM): proficiency in 2 of Animal Handling, Intimidation, Nature, Perception, Stealth, Survival. Children of Gruumsh rebuilt in MPMM away from racial stat penalties.',
    source: 'volos',
  },
  // ── Mordenkainen's Tome of Foes / MPMM ────────────────────────
  {
    slug: 'githyanki',
    name: 'Githyanki',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 INT',
    subraces: [],
    snippet: 'Astral-plane raiders. Mage Hand / Jump / Misty Step / Tongues innate.',
    description: '**Decadent Mastery**: 1 language + 1 skill proficiency of choice. **Martial Prodigy**: light + medium armor + shortsword/longsword/greatsword proficiency. **Githyanki Psionics**: Mage Hand at L1, Jump at L3, Misty Step at L5, Tongues at L5 — each 1/long rest (INT). Silver-skinned planar raiders that ride red dragons.',
    source: 'mtof',
  },
  {
    slug: 'githzerai',
    name: 'Githzerai',
    size: 'Medium',
    speed: 30,
    asi: '+2 WIS, +1 INT',
    subraces: [],
    snippet: 'Limbo-plane monks. Mental Discipline (adv vs charm/fright). Psionic innate.',
    description: '**Mental Discipline**: advantage on saves vs. charmed and frightened. **Githzerai Psionics**: Mage Hand at L1, Shield at L3, Detect Thoughts at L5 — each 1/long rest (WIS). Ascetic monks of the Outlands chaos-plane Limbo.',
    source: 'mtof',
  },
  // ── Eberron ─────────────────────────────────────────────────
  {
    slug: 'changeling',
    name: 'Changeling',
    size: 'Medium',
    speed: 30,
    asi: '+2 CHA, +1 any',
    subraces: [],
    snippet: 'Shapechanger (assume humanoid form). Unsettling Visage. Divergent Persona.',
    description: '**Shapechanger**: action — change appearance + voice of any medium/small humanoid you\'ve seen. Keep stats. **Changeling Instincts**: proficiency in 2 of Deception, Insight, Intimidation, Performance, Persuasion. **Divergent Persona**: secondary identity — one tool proficiency. Doppelganger-descendants; beloved spies + thieves.',
    source: 'eberron',
  },
  {
    slug: 'kalashtar',
    name: 'Kalashtar',
    size: 'Medium',
    speed: 30,
    asi: '+2 WIS, +1 CHA',
    subraces: [],
    snippet: 'Dual Mind. Mental Discipline (psychic resistance). Mind Link telepathy.',
    description: '**Dual Mind**: advantage on all WIS saves. **Mental Discipline**: resistance to psychic damage. **Mind Link**: telepathy with a willing creature within (10 × level) ft. **Severed from Dreams**: immune to spells that sense thoughts + dream-state effects. Humans bonded to good-aligned quori spirits from the plane Dal Quor.',
    source: 'eberron',
  },
  {
    slug: 'shifter',
    name: 'Shifter',
    size: 'Medium',
    speed: 30,
    asi: '+1 DEX; subrace adds more',
    subraces: ['Beasthide (+2 CON, temp HP + AC bonus)', 'Longtooth (+2 STR, bite attack)', 'Swiftstride (+2 DEX, bonus speed)', 'Wildhunt (+2 WIS, no surprise nearby)'],
    snippet: '60 ft darkvision. Shifting (bonus action, level-based temp HP + subrace bonus).',
    description: '**Darkvision 60 ft.** **Shifting**: bonus action — gain temp HP = level + CON mod, plus subrace trait, for 1 min (short rest recharge). Beasthide = +1 AC; Longtooth = bite 1d6 + STR; Swiftstride = +10 speed + disengage free; Wildhunt = advantage on WIS checks + no hidden surprise within 30 ft. Lycanthrope-descended shapeshifters.',
    source: 'eberron',
  },
  {
    slug: 'warforged',
    name: 'Warforged',
    size: 'Medium',
    speed: 30,
    asi: '+2 CON, +1 any',
    subraces: [],
    snippet: '+1 AC integrated. Constructed Resilience (sleep/poison immune). Sentry\'s Rest.',
    description: '**Constructed Resilience**: advantage on saves vs. poison, poison resistance, no need for food/water/air/sleep, immune to disease + magical sleep. **Sentry\'s Rest**: 6h conscious immobile = long rest. **Integrated Protection**: +1 AC baseline; armor can\'t be removed against your will. Living-constructs forged for the Last War.',
    source: 'eberron',
  },
  // ── Theros + general MPMM races ───────────────────────────────
  {
    slug: 'centaur',
    name: 'Centaur',
    size: 'Medium',
    speed: 40,
    asi: '+2 STR, +1 WIS',
    subraces: [],
    snippet: 'Fey (charm adv). Hooves 1d4+STR. 40 ft speed. Equine Build.',
    description: '**Creature Type: Fey**: advantage on charmed saves. **Hooves**: unarmed strike 1d4 + STR. **Equine Build**: count as one size larger for carrying + push/drag/lift; difficult to move through narrow passages. **40 ft speed**. **Survivor**: one Nature / Animal Handling / Medicine / Survival proficiency. Iconic in Theros; also MPMM.',
    source: 'theros',
  },
  {
    slug: 'leonin',
    name: 'Leonin',
    size: 'Medium',
    speed: 35,
    asi: '+2 STR, +1 CON',
    subraces: [],
    snippet: 'Daunting Roar action (frighten nearby enemies). Claws. 35 ft speed.',
    description: '**Daunting Roar**: bonus action — force WIS save (DC 8 + prof + CON) on creatures within 10 ft or they\'re frightened until end of your next turn. 1/short rest. **Claws**: 1d4 + STR unarmed. **Hunter\'s Instincts**: one Athletics/Intimidation/Perception/Survival proficiency. **Keen Smell**: adv on WIS(Perception) with smell. Lion-folk pride-dwellers from Oreskos.',
    source: 'theros',
  },
  {
    slug: 'minotaur',
    name: 'Minotaur',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 CON',
    subraces: [],
    snippet: 'Horns 1d6+STR. Goring Rush (after Dash, bonus-action gore). Hammering Horns (push).',
    description: '**Horns**: unarmed strike 1d6 + STR. **Goring Rush**: after using Dash action, attack with horns as bonus action. **Hammering Horns**: after hitting with horns on your turn, STR save or push 10 ft. **Menacing Presence**: proficiency in Intimidation. **Labyrinthine Recall**: perfect memory for any path traveled. Theros + Ravnica reprint.',
    source: 'theros',
  },
  // ── Wildemount / TCE / MPMM additions ────────────────────────
  {
    slug: 'tortle',
    name: 'Tortle',
    size: 'Medium',
    speed: 30,
    asi: '+2 STR, +1 WIS',
    subraces: [],
    snippet: 'Natural Armor 17 (no DEX). Claws. Shell Defense action (AC 20, incapacitated).',
    description: '**Claws**: 1d4 + STR unarmed. **Hold Breath 1 hr**. **Natural Armor 17** (no DEX mod, no shield). **Shell Defense**: action — withdraw into shell, AC 20, advantage on STR + CON saves, incapacitated until you emerge (action). **Survival Instinct**: Survival proficiency. Turtle-folk merchants + nomads.',
    source: 'tce',
  },
  {
    slug: 'fairy',
    name: 'Fairy',
    size: 'Small',
    speed: 30,
    asi: '+2 any, +1 any (TCE floating)',
    subraces: [],
    snippet: 'Fly 30 ft. Fey creature type. Druidcraft cantrip. Faerie Fire + Enlarge/Reduce innate.',
    description: '**Creature Type: Fey.** **Fairy Magic**: Druidcraft cantrip, Faerie Fire + Enlarge/Reduce once per long rest (INT/WIS/CHA). **Flight**: 30 ft fly speed. **Small size** — you can\'t wear medium/large armor and armor must fit your frame. Wildemount + Witchlight.',
    source: 'mpmm',
  },
  {
    slug: 'satyr',
    name: 'Satyr',
    size: 'Medium',
    speed: 35,
    asi: '+2 CHA, +1 DEX',
    subraces: [],
    snippet: 'Fey. Magic Resistance (adv vs all magic saves). Mirthful Leaps. Ram 1d4.',
    description: '**Creature Type: Fey.** **Magic Resistance**: advantage on saves vs. spells and magical effects. **Mirthful Leaps**: add d8 to your jump distance when jumping. **Reveler**: proficiency in Performance + Persuasion + one musical instrument. **Ram**: unarmed strike 1d4 + STR. **35 ft speed**. Revelers of Theros woodlands.',
    source: 'theros',
  },
  {
    slug: 'owlin',
    name: 'Owlin',
    size: 'Medium',
    speed: 30,
    asi: '+2 any, +1 any (floating)',
    subraces: [],
    snippet: '120 ft darkvision. Fly 30 ft. Silent Flight (stealthy).',
    description: '**Darkvision 120 ft.** **Flight**: 30 ft flying speed (no armor heavier than medium). **Silent Flight**: Stealth proficiency — can\'t be tracked by non-magical means while flying, unless you choose to leave evidence. Owl-folk academics from Strixhaven.',
    source: 'strixhaven',
  },
  {
    slug: 'eladrin',
    name: 'Eladrin',
    size: 'Medium',
    speed: 30,
    asi: '+2 DEX, +1 CHA (or INT)',
    subraces: ['Spring (charm)', 'Summer (fire dmg)', 'Autumn (calm)', 'Winter (fear)'],
    snippet: 'Fey. Fey Step (bonus action 30 ft teleport, season-flavored).',
    description: '**Darkvision 60 ft** + **Fey Ancestry**. **Trance** (same as elves). **Fey Step**: bonus action — teleport 30 ft. 1/short rest. Season changes when you finish a long rest: **Spring** (charm target on fey step), **Summer** (fire damage burst), **Autumn** (charm aura calming target), **Winter** (fear). MToF / MPMM.',
    source: 'mtof',
  },
  {
    slug: 'dragonborn-chromatic',
    name: 'Dragonborn (Chromatic — Fizban\'s)',
    size: 'Medium',
    speed: 30,
    asi: '+2 any, +1 any (floating)',
    subraces: ['Black (acid)', 'Blue (lightning)', 'Green (poison)', 'Red (fire)', 'White (cold)'],
    snippet: 'Chromatic Warding (L5: 1/long rest immune to your ancestry\'s damage).',
    description: '**Breath Weapon**: action — line/cone, DEX save, level-scaled dice of your ancestry\'s damage type. **Damage Resistance** to your ancestry type. **Chromatic Warding** (L5): action — become immune to your ancestry\'s damage type for 1 min, 1/long rest. Fizban\'s Treasury of Dragons update.',
    source: 'fizban',
  },
  {
    slug: 'dragonborn-metallic',
    name: 'Dragonborn (Metallic — Fizban\'s)',
    size: 'Medium',
    speed: 30,
    asi: '+2 any, +1 any (floating)',
    subraces: ['Brass (fire)', 'Bronze (lightning)', 'Copper (acid)', 'Gold (fire)', 'Silver (cold)'],
    snippet: 'Metallic Breath Weapon (L5: 2nd breath — enervating or repulsion).',
    description: '**Breath Weapon** + **Damage Resistance** by ancestry. **Metallic Breath Weapon** at L5: secondary exhalation — Enervating (incapacitate for 1 turn) or Repulsion (push 20 ft), 1/long rest. Fizban\'s Treasury of Dragons.',
    source: 'fizban',
  },
  {
    slug: 'dragonborn-gem',
    name: 'Dragonborn (Gem — Fizban\'s)',
    size: 'Medium',
    speed: 30,
    asi: '+2 any, +1 any (floating)',
    subraces: ['Amethyst (force)', 'Crystal (radiant)', 'Emerald (psychic)', 'Sapphire (thunder)', 'Topaz (necrotic)'],
    snippet: 'Psionic Mind telepathy. Gemstone Flight at L5 (20-ft fly 1 min).',
    description: '**Breath Weapon** + **Damage Resistance** (psionic-aligned types). **Psionic Mind**: 30 ft telepathy. **Gemstone Flight** at L5: bonus action — sprout crystalline wings, 20 ft fly speed for 1 min, 1/long rest. Fizban\'s Treasury of Dragons.',
    source: 'fizban',
  },
  {
    slug: 'harengon',
    name: 'Harengon',
    size: 'Medium',
    speed: 30,
    asi: '+2 any, +1 any (floating)',
    subraces: [],
    snippet: 'Fey. Hare-Trigger (reaction add prof to init). Lucky Footwork reaction.',
    description: '**Creature Type: Fey.** **Hare-Trigger**: add proficiency bonus to initiative rolls. **Leporine Senses**: proficiency in Perception. **Lucky Footwork**: reaction when you fail a DEX save — roll d4 and add to the save (1/turn). **Rabbit Hop**: bonus action — jump equal to 5 × prof bonus in feet, prof-bonus uses per long rest. Wildemount / Witchlight.',
    source: 'witchlight',
  },
];
